#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 85
#define LARGE_STATE_COUNT 8
#define SYMBOL_COUNT 55
#define ALIAS_COUNT 1
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 12
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 18

enum ts_symbol_identifiers {
  sym_ident = 1,
  anon_sym_namespace = 2,
  anon_sym_SEMI = 3,
  sym_comment = 4,
  anon_sym_PLUS = 5,
  anon_sym_DASH = 6,
  anon_sym_STAR = 7,
  anon_sym_SLASH = 8,
  sym_int_lit = 9,
  sym_str_lit = 10,
  anon_sym_true = 11,
  anon_sym_false = 12,
  anon_sym_COLON = 13,
  anon_sym_BSLASH = 14,
  anon_sym_LBRACK = 15,
  anon_sym_LPAREN = 16,
  anon_sym_LBRACK_RBRACK = 17,
  anon_sym_DOT = 18,
  anon_sym_RPAREN = 19,
  anon_sym_RBRACK = 20,
  anon_sym_EQ = 21,
  aux_sym_attr_token1 = 22,
  anon_sym_record = 23,
  anon_sym_end = 24,
  anon_sym_do = 25,
  anon_sym_templ = 26,
  sym_source = 27,
  sym_namespace = 28,
  sym_sym = 29,
  sym_bool_lit = 30,
  sym_kwd_lit = 31,
  sym_escape = 32,
  sym__def = 33,
  sym__form = 34,
  sym__type = 35,
  sym_attrs = 36,
  sym_slice_lit = 37,
  sym_field_access = 38,
  sym_fields = 39,
  sym_field = 40,
  sym__expr = 41,
  sym_list_lit = 42,
  sym_element = 43,
  aux_sym__elements = 44,
  sym_attr = 45,
  sym_def_record = 46,
  sym__record_body = 47,
  sym_def_templ = 48,
  sym__templ_body = 49,
  aux_sym_source_repeat1 = 50,
  aux_sym_attrs_repeat1 = 51,
  aux_sym_fields_repeat1 = 52,
  aux_sym_list_lit_repeat1 = 53,
  aux_sym__templ_body_repeat1 = 54,
  alias_sym_children = 55,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_ident] = "ident",
  [anon_sym_namespace] = "namespace",
  [anon_sym_SEMI] = ";",
  [sym_comment] = "comment",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [sym_int_lit] = "int_lit",
  [sym_str_lit] = "str_lit",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_COLON] = ":",
  [anon_sym_BSLASH] = "\\",
  [anon_sym_LBRACK] = "[",
  [anon_sym_LPAREN] = "(",
  [anon_sym_LBRACK_RBRACK] = "[]",
  [anon_sym_DOT] = ".",
  [anon_sym_RPAREN] = ")",
  [anon_sym_RBRACK] = "]",
  [anon_sym_EQ] = "=",
  [aux_sym_attr_token1] = "text",
  [anon_sym_record] = "record",
  [anon_sym_end] = "end",
  [anon_sym_do] = "do",
  [anon_sym_templ] = "templ",
  [sym_source] = "source",
  [sym_namespace] = "namespace",
  [sym_sym] = "sym",
  [sym_bool_lit] = "bool_lit",
  [sym_kwd_lit] = "kwd_lit",
  [sym_escape] = "escape",
  [sym__def] = "_def",
  [sym__form] = "_form",
  [sym__type] = "_type",
  [sym_attrs] = "attrs",
  [sym_slice_lit] = "slice_lit",
  [sym_field_access] = "field_access",
  [sym_fields] = "fields",
  [sym_field] = "field",
  [sym__expr] = "_expr",
  [sym_list_lit] = "list_lit",
  [sym_element] = "element",
  [aux_sym__elements] = "_elements",
  [sym_attr] = "attr",
  [sym_def_record] = "def_record",
  [sym__record_body] = "_record_body",
  [sym_def_templ] = "def_templ",
  [sym__templ_body] = "body",
  [aux_sym_source_repeat1] = "source_repeat1",
  [aux_sym_attrs_repeat1] = "attrs_repeat1",
  [aux_sym_fields_repeat1] = "fields_repeat1",
  [aux_sym_list_lit_repeat1] = "list_lit_repeat1",
  [aux_sym__templ_body_repeat1] = "_templ_body_repeat1",
  [alias_sym_children] = "children",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_ident] = sym_ident,
  [anon_sym_namespace] = anon_sym_namespace,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym_comment] = sym_comment,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [sym_int_lit] = sym_int_lit,
  [sym_str_lit] = sym_str_lit,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_LBRACK_RBRACK] = anon_sym_LBRACK_RBRACK,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_EQ] = anon_sym_EQ,
  [aux_sym_attr_token1] = aux_sym_attr_token1,
  [anon_sym_record] = anon_sym_record,
  [anon_sym_end] = anon_sym_end,
  [anon_sym_do] = anon_sym_do,
  [anon_sym_templ] = anon_sym_templ,
  [sym_source] = sym_source,
  [sym_namespace] = sym_namespace,
  [sym_sym] = sym_sym,
  [sym_bool_lit] = sym_bool_lit,
  [sym_kwd_lit] = sym_kwd_lit,
  [sym_escape] = sym_escape,
  [sym__def] = sym__def,
  [sym__form] = sym__form,
  [sym__type] = sym__type,
  [sym_attrs] = sym_attrs,
  [sym_slice_lit] = sym_slice_lit,
  [sym_field_access] = sym_field_access,
  [sym_fields] = sym_fields,
  [sym_field] = sym_field,
  [sym__expr] = sym__expr,
  [sym_list_lit] = sym_list_lit,
  [sym_element] = sym_element,
  [aux_sym__elements] = aux_sym__elements,
  [sym_attr] = sym_attr,
  [sym_def_record] = sym_def_record,
  [sym__record_body] = sym__record_body,
  [sym_def_templ] = sym_def_templ,
  [sym__templ_body] = sym__templ_body,
  [aux_sym_source_repeat1] = aux_sym_source_repeat1,
  [aux_sym_attrs_repeat1] = aux_sym_attrs_repeat1,
  [aux_sym_fields_repeat1] = aux_sym_fields_repeat1,
  [aux_sym_list_lit_repeat1] = aux_sym_list_lit_repeat1,
  [aux_sym__templ_body_repeat1] = aux_sym__templ_body_repeat1,
  [alias_sym_children] = alias_sym_children,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_namespace] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_int_lit] = {
    .visible = true,
    .named = true,
  },
  [sym_str_lit] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_attr_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_record] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_end] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_do] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_templ] = {
    .visible = true,
    .named = false,
  },
  [sym_source] = {
    .visible = true,
    .named = true,
  },
  [sym_namespace] = {
    .visible = true,
    .named = true,
  },
  [sym_sym] = {
    .visible = true,
    .named = true,
  },
  [sym_bool_lit] = {
    .visible = true,
    .named = true,
  },
  [sym_kwd_lit] = {
    .visible = true,
    .named = true,
  },
  [sym_escape] = {
    .visible = true,
    .named = true,
  },
  [sym__def] = {
    .visible = false,
    .named = true,
  },
  [sym__form] = {
    .visible = false,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym_attrs] = {
    .visible = true,
    .named = true,
  },
  [sym_slice_lit] = {
    .visible = true,
    .named = true,
  },
  [sym_field_access] = {
    .visible = true,
    .named = true,
  },
  [sym_fields] = {
    .visible = true,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym__expr] = {
    .visible = false,
    .named = true,
  },
  [sym_list_lit] = {
    .visible = true,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__elements] = {
    .visible = false,
    .named = false,
  },
  [sym_attr] = {
    .visible = true,
    .named = true,
  },
  [sym_def_record] = {
    .visible = true,
    .named = true,
  },
  [sym__record_body] = {
    .visible = false,
    .named = true,
  },
  [sym_def_templ] = {
    .visible = true,
    .named = true,
  },
  [sym__templ_body] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_attrs_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_fields_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_lit_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__templ_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_children] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_close = 2,
  field_field = 3,
  field_key = 4,
  field_marker = 5,
  field_name = 6,
  field_object = 7,
  field_open = 8,
  field_tag = 9,
  field_type = 10,
  field_value = 11,
  field_var = 12,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_close] = "close",
  [field_field] = "field",
  [field_key] = "key",
  [field_marker] = "marker",
  [field_name] = "name",
  [field_object] = "object",
  [field_open] = "open",
  [field_tag] = "tag",
  [field_type] = "type",
  [field_value] = "value",
  [field_var] = "var",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 3},
  [6] = {.index = 9, .length = 3},
  [7] = {.index = 12, .length = 2},
  [8] = {.index = 14, .length = 3},
  [9] = {.index = 17, .length = 3},
  [10] = {.index = 17, .length = 3},
  [11] = {.index = 20, .length = 1},
  [12] = {.index = 21, .length = 5},
  [13] = {.index = 26, .length = 4},
  [14] = {.index = 30, .length = 2},
  [15] = {.index = 32, .length = 3},
  [16] = {.index = 35, .length = 5},
  [17] = {.index = 40, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_marker, 0},
    {field_name, 1},
  [2] =
    {field_value, 0},
  [3] =
    {field_name, 1},
  [4] =
    {field_field, 2},
    {field_object, 0},
  [6] =
    {field_close, 2},
    {field_open, 0},
    {field_tag, 1},
  [9] =
    {field_close, 2},
    {field_open, 0},
    {field_value, 1, .inherited = true},
  [12] =
    {field_value, 0, .inherited = true},
    {field_value, 1, .inherited = true},
  [14] =
    {field_close, 2},
    {field_name, 1},
    {field_open, 0},
  [17] =
    {field_close, 3},
    {field_open, 0},
    {field_tag, 1},
  [20] =
    {field_marker, 0},
  [21] =
    {field_body, 2},
    {field_close, 3},
    {field_marker, 2, .inherited = true},
    {field_name, 1},
    {field_open, 0},
  [26] =
    {field_close, 3},
    {field_open, 0},
    {field_type, 2},
    {field_var, 1},
  [30] =
    {field_key, 0},
    {field_value, 2},
  [32] =
    {field_close, 4},
    {field_open, 0},
    {field_tag, 1},
  [35] =
    {field_close, 4},
    {field_marker, 3, .inherited = true},
    {field_open, 0},
    {field_type, 2},
    {field_var, 1},
  [40] =
    {field_name, 0},
    {field_type, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [10] = {
    [2] = alias_sym_children,
  },
  [15] = {
    [3] = alias_sym_children,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  aux_sym__elements, 2,
    aux_sym__elements,
    alias_sym_children,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 6,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 11,
  [14] = 14,
  [15] = 14,
  [16] = 16,
  [17] = 9,
  [18] = 16,
  [19] = 19,
  [20] = 20,
  [21] = 20,
  [22] = 22,
  [23] = 23,
  [24] = 23,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 26,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 25,
  [40] = 37,
  [41] = 34,
  [42] = 32,
  [43] = 35,
  [44] = 27,
  [45] = 45,
  [46] = 46,
  [47] = 29,
  [48] = 28,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 45,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 61,
  [63] = 63,
  [64] = 64,
  [65] = 64,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 68,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 75,
  [82] = 82,
  [83] = 83,
  [84] = 84,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      ADVANCE_MAP(
        '"', 1,
        '#', 13,
        '\'', 3,
        '(', 26,
        ')', 29,
        '*', 18,
        '+', 16,
        '-', 17,
        '.', 28,
        '/', 19,
        '0', 20,
        ':', 23,
        ';', 7,
        '=', 31,
        '[', 25,
        '\\', 24,
        ']', 30,
        '_', 9,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(21);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(12);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(22);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(13);
      if (lookahead == '[') ADVANCE(4);
      if (lookahead == '_') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(12);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(22);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == ']') ADVANCE(27);
      END_STATE();
    case 5:
      if (eof) ADVANCE(6);
      ADVANCE_MAP(
        '"', 1,
        '#', 13,
        '\'', 3,
        '(', 26,
        ')', 29,
        '*', 18,
        '+', 16,
        '-', 17,
        '.', 28,
        '/', 19,
        '0', 20,
        ':', 23,
        ';', 7,
        '[', 25,
        '\\', 24,
        ']', 30,
        '_', 9,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(21);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(12);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '-') ADVANCE(10);
      if (lookahead == '_') ADVANCE(11);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(12);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '_') ADVANCE(11);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(12);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '-' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_ident);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead == '#') ADVANCE(13);
      if (lookahead != 0) ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead == '#') ADVANCE(14);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == ']') ADVANCE(13);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '#') ADVANCE(13);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_int_lit);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_int_lit);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_str_lit);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LBRACK_RBRACK);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_attr_token1);
      if (lookahead == '#') ADVANCE(14);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ']') ADVANCE(33);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_attr_token1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ']') ADVANCE(33);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'd') ADVANCE(1);
      if (lookahead == 'e') ADVANCE(2);
      if (lookahead == 'f') ADVANCE(3);
      if (lookahead == 'n') ADVANCE(4);
      if (lookahead == 'r') ADVANCE(5);
      if (lookahead == 't') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'o') ADVANCE(7);
      END_STATE();
    case 2:
      if (lookahead == 'n') ADVANCE(8);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(9);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(10);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(11);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(12);
      if (lookahead == 'r') ADVANCE(13);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_do);
      END_STATE();
    case 8:
      if (lookahead == 'd') ADVANCE(14);
      END_STATE();
    case 9:
      if (lookahead == 'l') ADVANCE(15);
      END_STATE();
    case 10:
      if (lookahead == 'm') ADVANCE(16);
      END_STATE();
    case 11:
      if (lookahead == 'c') ADVANCE(17);
      END_STATE();
    case 12:
      if (lookahead == 'm') ADVANCE(18);
      END_STATE();
    case 13:
      if (lookahead == 'u') ADVANCE(19);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_end);
      END_STATE();
    case 15:
      if (lookahead == 's') ADVANCE(20);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 17:
      if (lookahead == 'o') ADVANCE(22);
      END_STATE();
    case 18:
      if (lookahead == 'p') ADVANCE(23);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(25);
      END_STATE();
    case 21:
      if (lookahead == 's') ADVANCE(26);
      END_STATE();
    case 22:
      if (lookahead == 'r') ADVANCE(27);
      END_STATE();
    case 23:
      if (lookahead == 'l') ADVANCE(28);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 26:
      if (lookahead == 'p') ADVANCE(29);
      END_STATE();
    case 27:
      if (lookahead == 'd') ADVANCE(30);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_templ);
      END_STATE();
    case 29:
      if (lookahead == 'a') ADVANCE(31);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_record);
      END_STATE();
    case 31:
      if (lookahead == 'c') ADVANCE(32);
      END_STATE();
    case 32:
      if (lookahead == 'e') ADVANCE(33);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_namespace);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 2},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 32},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_ident] = ACTIONS(1),
    [anon_sym_namespace] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [sym_int_lit] = ACTIONS(1),
    [sym_str_lit] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_record] = ACTIONS(1),
    [anon_sym_end] = ACTIONS(1),
    [anon_sym_do] = ACTIONS(1),
    [anon_sym_templ] = ACTIONS(1),
  },
  [1] = {
    [sym_source] = STATE(76),
    [sym_namespace] = STATE(4),
    [sym_sym] = STATE(3),
    [sym_bool_lit] = STATE(3),
    [sym_kwd_lit] = STATE(3),
    [sym_escape] = STATE(3),
    [sym__def] = STATE(3),
    [sym__form] = STATE(3),
    [sym_field_access] = STATE(3),
    [sym__expr] = STATE(3),
    [sym_list_lit] = STATE(3),
    [sym_element] = STATE(3),
    [sym_def_record] = STATE(3),
    [sym_def_templ] = STATE(3),
    [aux_sym_source_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_ident] = ACTIONS(7),
    [anon_sym_namespace] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
    [anon_sym_PLUS] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_STAR] = ACTIONS(11),
    [anon_sym_SLASH] = ACTIONS(11),
    [sym_int_lit] = ACTIONS(13),
    [sym_str_lit] = ACTIONS(13),
    [anon_sym_true] = ACTIONS(15),
    [anon_sym_false] = ACTIONS(15),
    [anon_sym_COLON] = ACTIONS(17),
    [anon_sym_BSLASH] = ACTIONS(19),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_record] = ACTIONS(25),
    [anon_sym_templ] = ACTIONS(27),
  },
  [2] = {
    [sym_sym] = STATE(5),
    [sym_bool_lit] = STATE(5),
    [sym_kwd_lit] = STATE(5),
    [sym_escape] = STATE(5),
    [sym__def] = STATE(5),
    [sym__form] = STATE(5),
    [sym_field_access] = STATE(5),
    [sym__expr] = STATE(5),
    [sym_list_lit] = STATE(5),
    [sym_element] = STATE(5),
    [sym_def_record] = STATE(5),
    [sym_def_templ] = STATE(5),
    [aux_sym_source_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(29),
    [sym_ident] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
    [anon_sym_PLUS] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_STAR] = ACTIONS(11),
    [anon_sym_SLASH] = ACTIONS(11),
    [sym_int_lit] = ACTIONS(31),
    [sym_str_lit] = ACTIONS(31),
    [anon_sym_true] = ACTIONS(15),
    [anon_sym_false] = ACTIONS(15),
    [anon_sym_COLON] = ACTIONS(17),
    [anon_sym_BSLASH] = ACTIONS(19),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_record] = ACTIONS(25),
    [anon_sym_templ] = ACTIONS(27),
  },
  [3] = {
    [sym_sym] = STATE(5),
    [sym_bool_lit] = STATE(5),
    [sym_kwd_lit] = STATE(5),
    [sym_escape] = STATE(5),
    [sym__def] = STATE(5),
    [sym__form] = STATE(5),
    [sym_field_access] = STATE(5),
    [sym__expr] = STATE(5),
    [sym_list_lit] = STATE(5),
    [sym_element] = STATE(5),
    [sym_def_record] = STATE(5),
    [sym_def_templ] = STATE(5),
    [aux_sym_source_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(33),
    [sym_ident] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
    [anon_sym_PLUS] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_STAR] = ACTIONS(11),
    [anon_sym_SLASH] = ACTIONS(11),
    [sym_int_lit] = ACTIONS(31),
    [sym_str_lit] = ACTIONS(31),
    [anon_sym_true] = ACTIONS(15),
    [anon_sym_false] = ACTIONS(15),
    [anon_sym_COLON] = ACTIONS(17),
    [anon_sym_BSLASH] = ACTIONS(19),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_record] = ACTIONS(25),
    [anon_sym_templ] = ACTIONS(27),
  },
  [4] = {
    [sym_sym] = STATE(2),
    [sym_bool_lit] = STATE(2),
    [sym_kwd_lit] = STATE(2),
    [sym_escape] = STATE(2),
    [sym__def] = STATE(2),
    [sym__form] = STATE(2),
    [sym_field_access] = STATE(2),
    [sym__expr] = STATE(2),
    [sym_list_lit] = STATE(2),
    [sym_element] = STATE(2),
    [sym_def_record] = STATE(2),
    [sym_def_templ] = STATE(2),
    [aux_sym_source_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(33),
    [sym_ident] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
    [anon_sym_PLUS] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_STAR] = ACTIONS(11),
    [anon_sym_SLASH] = ACTIONS(11),
    [sym_int_lit] = ACTIONS(35),
    [sym_str_lit] = ACTIONS(35),
    [anon_sym_true] = ACTIONS(15),
    [anon_sym_false] = ACTIONS(15),
    [anon_sym_COLON] = ACTIONS(17),
    [anon_sym_BSLASH] = ACTIONS(19),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_record] = ACTIONS(25),
    [anon_sym_templ] = ACTIONS(27),
  },
  [5] = {
    [sym_sym] = STATE(5),
    [sym_bool_lit] = STATE(5),
    [sym_kwd_lit] = STATE(5),
    [sym_escape] = STATE(5),
    [sym__def] = STATE(5),
    [sym__form] = STATE(5),
    [sym_field_access] = STATE(5),
    [sym__expr] = STATE(5),
    [sym_list_lit] = STATE(5),
    [sym_element] = STATE(5),
    [sym_def_record] = STATE(5),
    [sym_def_templ] = STATE(5),
    [aux_sym_source_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(37),
    [sym_ident] = ACTIONS(39),
    [sym_comment] = ACTIONS(3),
    [anon_sym_PLUS] = ACTIONS(42),
    [anon_sym_DASH] = ACTIONS(42),
    [anon_sym_STAR] = ACTIONS(42),
    [anon_sym_SLASH] = ACTIONS(42),
    [sym_int_lit] = ACTIONS(45),
    [sym_str_lit] = ACTIONS(45),
    [anon_sym_true] = ACTIONS(48),
    [anon_sym_false] = ACTIONS(48),
    [anon_sym_COLON] = ACTIONS(51),
    [anon_sym_BSLASH] = ACTIONS(54),
    [anon_sym_LBRACK] = ACTIONS(57),
    [anon_sym_LPAREN] = ACTIONS(60),
    [anon_sym_record] = ACTIONS(63),
    [anon_sym_templ] = ACTIONS(66),
  },
  [6] = {
    [sym_sym] = STATE(55),
    [sym_bool_lit] = STATE(55),
    [sym_kwd_lit] = STATE(55),
    [sym_escape] = STATE(55),
    [sym__form] = STATE(55),
    [sym_attrs] = STATE(11),
    [sym_field_access] = STATE(55),
    [sym__expr] = STATE(55),
    [sym_list_lit] = STATE(55),
    [sym_element] = STATE(55),
    [aux_sym__elements] = STATE(15),
    [sym_attr] = STATE(36),
    [aux_sym_attrs_repeat1] = STATE(36),
    [sym_ident] = ACTIONS(69),
    [sym_comment] = ACTIONS(3),
    [anon_sym_PLUS] = ACTIONS(71),
    [anon_sym_DASH] = ACTIONS(71),
    [anon_sym_STAR] = ACTIONS(71),
    [anon_sym_SLASH] = ACTIONS(71),
    [sym_int_lit] = ACTIONS(73),
    [sym_str_lit] = ACTIONS(73),
    [anon_sym_true] = ACTIONS(75),
    [anon_sym_false] = ACTIONS(75),
    [anon_sym_COLON] = ACTIONS(77),
    [anon_sym_BSLASH] = ACTIONS(79),
    [anon_sym_LBRACK] = ACTIONS(81),
    [anon_sym_LPAREN] = ACTIONS(83),
    [anon_sym_RBRACK] = ACTIONS(85),
  },
  [7] = {
    [sym_sym] = STATE(55),
    [sym_bool_lit] = STATE(55),
    [sym_kwd_lit] = STATE(55),
    [sym_escape] = STATE(55),
    [sym__form] = STATE(55),
    [sym_attrs] = STATE(13),
    [sym_field_access] = STATE(55),
    [sym__expr] = STATE(55),
    [sym_list_lit] = STATE(55),
    [sym_element] = STATE(55),
    [aux_sym__elements] = STATE(14),
    [sym_attr] = STATE(36),
    [aux_sym_attrs_repeat1] = STATE(36),
    [sym_ident] = ACTIONS(69),
    [sym_comment] = ACTIONS(3),
    [anon_sym_PLUS] = ACTIONS(71),
    [anon_sym_DASH] = ACTIONS(71),
    [anon_sym_STAR] = ACTIONS(71),
    [anon_sym_SLASH] = ACTIONS(71),
    [sym_int_lit] = ACTIONS(73),
    [sym_str_lit] = ACTIONS(73),
    [anon_sym_true] = ACTIONS(75),
    [anon_sym_false] = ACTIONS(75),
    [anon_sym_COLON] = ACTIONS(77),
    [anon_sym_BSLASH] = ACTIONS(79),
    [anon_sym_LBRACK] = ACTIONS(81),
    [anon_sym_LPAREN] = ACTIONS(83),
    [anon_sym_RBRACK] = ACTIONS(87),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      anon_sym_COLON,
    ACTIONS(79), 1,
      anon_sym_BSLASH,
    ACTIONS(81), 1,
      anon_sym_LBRACK,
    ACTIONS(83), 1,
      anon_sym_LPAREN,
    ACTIONS(89), 1,
      sym_ident,
    ACTIONS(93), 1,
      anon_sym_end,
    ACTIONS(75), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(91), 2,
      sym_int_lit,
      sym_str_lit,
    ACTIONS(71), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(10), 10,
      sym_sym,
      sym_bool_lit,
      sym_kwd_lit,
      sym_escape,
      sym__form,
      sym_field_access,
      sym__expr,
      sym_list_lit,
      sym_element,
      aux_sym__templ_body_repeat1,
  [48] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      anon_sym_COLON,
    ACTIONS(79), 1,
      anon_sym_BSLASH,
    ACTIONS(81), 1,
      anon_sym_LBRACK,
    ACTIONS(83), 1,
      anon_sym_LPAREN,
    ACTIONS(89), 1,
      sym_ident,
    ACTIONS(97), 1,
      anon_sym_RPAREN,
    STATE(19), 1,
      aux_sym_list_lit_repeat1,
    ACTIONS(75), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(95), 2,
      sym_int_lit,
      sym_str_lit,
    ACTIONS(71), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(54), 9,
      sym_sym,
      sym_bool_lit,
      sym_kwd_lit,
      sym_escape,
      sym__form,
      sym_field_access,
      sym__expr,
      sym_list_lit,
      sym_element,
  [98] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      sym_ident,
    ACTIONS(111), 1,
      anon_sym_COLON,
    ACTIONS(114), 1,
      anon_sym_BSLASH,
    ACTIONS(117), 1,
      anon_sym_LBRACK,
    ACTIONS(120), 1,
      anon_sym_LPAREN,
    ACTIONS(123), 1,
      anon_sym_end,
    ACTIONS(105), 2,
      sym_int_lit,
      sym_str_lit,
    ACTIONS(108), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(102), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(10), 10,
      sym_sym,
      sym_bool_lit,
      sym_kwd_lit,
      sym_escape,
      sym__form,
      sym_field_access,
      sym__expr,
      sym_list_lit,
      sym_element,
      aux_sym__templ_body_repeat1,
  [146] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      anon_sym_COLON,
    ACTIONS(79), 1,
      anon_sym_BSLASH,
    ACTIONS(81), 1,
      anon_sym_LBRACK,
    ACTIONS(83), 1,
      anon_sym_LPAREN,
    ACTIONS(89), 1,
      sym_ident,
    ACTIONS(125), 1,
      anon_sym_RBRACK,
    STATE(18), 1,
      aux_sym__elements,
    ACTIONS(73), 2,
      sym_int_lit,
      sym_str_lit,
    ACTIONS(75), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(71), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(55), 9,
      sym_sym,
      sym_bool_lit,
      sym_kwd_lit,
      sym_escape,
      sym__form,
      sym_field_access,
      sym__expr,
      sym_list_lit,
      sym_element,
  [196] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      sym_ident,
    ACTIONS(139), 1,
      anon_sym_COLON,
    ACTIONS(142), 1,
      anon_sym_BSLASH,
    ACTIONS(145), 1,
      anon_sym_LBRACK,
    ACTIONS(148), 1,
      anon_sym_LPAREN,
    ACTIONS(151), 1,
      anon_sym_RBRACK,
    STATE(12), 1,
      aux_sym__elements,
    ACTIONS(133), 2,
      sym_int_lit,
      sym_str_lit,
    ACTIONS(136), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(130), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(55), 9,
      sym_sym,
      sym_bool_lit,
      sym_kwd_lit,
      sym_escape,
      sym__form,
      sym_field_access,
      sym__expr,
      sym_list_lit,
      sym_element,
  [246] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      anon_sym_COLON,
    ACTIONS(79), 1,
      anon_sym_BSLASH,
    ACTIONS(81), 1,
      anon_sym_LBRACK,
    ACTIONS(83), 1,
      anon_sym_LPAREN,
    ACTIONS(89), 1,
      sym_ident,
    ACTIONS(153), 1,
      anon_sym_RBRACK,
    STATE(16), 1,
      aux_sym__elements,
    ACTIONS(73), 2,
      sym_int_lit,
      sym_str_lit,
    ACTIONS(75), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(71), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(55), 9,
      sym_sym,
      sym_bool_lit,
      sym_kwd_lit,
      sym_escape,
      sym__form,
      sym_field_access,
      sym__expr,
      sym_list_lit,
      sym_element,
  [296] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      anon_sym_COLON,
    ACTIONS(79), 1,
      anon_sym_BSLASH,
    ACTIONS(81), 1,
      anon_sym_LBRACK,
    ACTIONS(83), 1,
      anon_sym_LPAREN,
    ACTIONS(89), 1,
      sym_ident,
    ACTIONS(155), 1,
      anon_sym_RBRACK,
    STATE(12), 1,
      aux_sym__elements,
    ACTIONS(73), 2,
      sym_int_lit,
      sym_str_lit,
    ACTIONS(75), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(71), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(55), 9,
      sym_sym,
      sym_bool_lit,
      sym_kwd_lit,
      sym_escape,
      sym__form,
      sym_field_access,
      sym__expr,
      sym_list_lit,
      sym_element,
  [346] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      anon_sym_COLON,
    ACTIONS(79), 1,
      anon_sym_BSLASH,
    ACTIONS(81), 1,
      anon_sym_LBRACK,
    ACTIONS(83), 1,
      anon_sym_LPAREN,
    ACTIONS(89), 1,
      sym_ident,
    ACTIONS(157), 1,
      anon_sym_RBRACK,
    STATE(12), 1,
      aux_sym__elements,
    ACTIONS(73), 2,
      sym_int_lit,
      sym_str_lit,
    ACTIONS(75), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(71), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(55), 9,
      sym_sym,
      sym_bool_lit,
      sym_kwd_lit,
      sym_escape,
      sym__form,
      sym_field_access,
      sym__expr,
      sym_list_lit,
      sym_element,
  [396] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      anon_sym_COLON,
    ACTIONS(79), 1,
      anon_sym_BSLASH,
    ACTIONS(81), 1,
      anon_sym_LBRACK,
    ACTIONS(83), 1,
      anon_sym_LPAREN,
    ACTIONS(89), 1,
      sym_ident,
    ACTIONS(159), 1,
      anon_sym_RBRACK,
    STATE(12), 1,
      aux_sym__elements,
    ACTIONS(73), 2,
      sym_int_lit,
      sym_str_lit,
    ACTIONS(75), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(71), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(55), 9,
      sym_sym,
      sym_bool_lit,
      sym_kwd_lit,
      sym_escape,
      sym__form,
      sym_field_access,
      sym__expr,
      sym_list_lit,
      sym_element,
  [446] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      anon_sym_COLON,
    ACTIONS(79), 1,
      anon_sym_BSLASH,
    ACTIONS(81), 1,
      anon_sym_LBRACK,
    ACTIONS(83), 1,
      anon_sym_LPAREN,
    ACTIONS(89), 1,
      sym_ident,
    ACTIONS(161), 1,
      anon_sym_RPAREN,
    STATE(19), 1,
      aux_sym_list_lit_repeat1,
    ACTIONS(75), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(95), 2,
      sym_int_lit,
      sym_str_lit,
    ACTIONS(71), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(54), 9,
      sym_sym,
      sym_bool_lit,
      sym_kwd_lit,
      sym_escape,
      sym__form,
      sym_field_access,
      sym__expr,
      sym_list_lit,
      sym_element,
  [496] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      anon_sym_COLON,
    ACTIONS(79), 1,
      anon_sym_BSLASH,
    ACTIONS(81), 1,
      anon_sym_LBRACK,
    ACTIONS(83), 1,
      anon_sym_LPAREN,
    ACTIONS(89), 1,
      sym_ident,
    ACTIONS(163), 1,
      anon_sym_RBRACK,
    STATE(12), 1,
      aux_sym__elements,
    ACTIONS(73), 2,
      sym_int_lit,
      sym_str_lit,
    ACTIONS(75), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(71), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(55), 9,
      sym_sym,
      sym_bool_lit,
      sym_kwd_lit,
      sym_escape,
      sym__form,
      sym_field_access,
      sym__expr,
      sym_list_lit,
      sym_element,
  [546] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      sym_ident,
    ACTIONS(177), 1,
      anon_sym_COLON,
    ACTIONS(180), 1,
      anon_sym_BSLASH,
    ACTIONS(183), 1,
      anon_sym_LBRACK,
    ACTIONS(186), 1,
      anon_sym_LPAREN,
    ACTIONS(189), 1,
      anon_sym_RPAREN,
    STATE(19), 1,
      aux_sym_list_lit_repeat1,
    ACTIONS(171), 2,
      sym_int_lit,
      sym_str_lit,
    ACTIONS(174), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(168), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(54), 9,
      sym_sym,
      sym_bool_lit,
      sym_kwd_lit,
      sym_escape,
      sym__form,
      sym_field_access,
      sym__expr,
      sym_list_lit,
      sym_element,
  [596] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      anon_sym_COLON,
    ACTIONS(79), 1,
      anon_sym_BSLASH,
    ACTIONS(81), 1,
      anon_sym_LBRACK,
    ACTIONS(83), 1,
      anon_sym_LPAREN,
    ACTIONS(89), 1,
      sym_ident,
    STATE(17), 1,
      aux_sym_list_lit_repeat1,
    ACTIONS(75), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(95), 2,
      sym_int_lit,
      sym_str_lit,
    ACTIONS(71), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(54), 9,
      sym_sym,
      sym_bool_lit,
      sym_kwd_lit,
      sym_escape,
      sym__form,
      sym_field_access,
      sym__expr,
      sym_list_lit,
      sym_element,
  [643] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      anon_sym_COLON,
    ACTIONS(79), 1,
      anon_sym_BSLASH,
    ACTIONS(81), 1,
      anon_sym_LBRACK,
    ACTIONS(83), 1,
      anon_sym_LPAREN,
    ACTIONS(89), 1,
      sym_ident,
    STATE(9), 1,
      aux_sym_list_lit_repeat1,
    ACTIONS(75), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(95), 2,
      sym_int_lit,
      sym_str_lit,
    ACTIONS(71), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(54), 9,
      sym_sym,
      sym_bool_lit,
      sym_kwd_lit,
      sym_escape,
      sym__form,
      sym_field_access,
      sym__expr,
      sym_list_lit,
      sym_element,
  [690] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      anon_sym_COLON,
    ACTIONS(79), 1,
      anon_sym_BSLASH,
    ACTIONS(81), 1,
      anon_sym_LBRACK,
    ACTIONS(83), 1,
      anon_sym_LPAREN,
    ACTIONS(89), 1,
      sym_ident,
    ACTIONS(75), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(191), 2,
      sym_int_lit,
      sym_str_lit,
    ACTIONS(71), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(8), 10,
      sym_sym,
      sym_bool_lit,
      sym_kwd_lit,
      sym_escape,
      sym__form,
      sym_field_access,
      sym__expr,
      sym_list_lit,
      sym_element,
      aux_sym__templ_body_repeat1,
  [735] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 1,
      anon_sym_DOT,
    ACTIONS(193), 4,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_end,
    ACTIONS(195), 12,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      sym_str_lit,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [762] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 1,
      anon_sym_DOT,
    ACTIONS(193), 5,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_record,
      anon_sym_templ,
    ACTIONS(195), 11,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      sym_str_lit,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [789] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 5,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_record,
      anon_sym_templ,
    ACTIONS(201), 11,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      sym_str_lit,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [813] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 5,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_record,
      anon_sym_templ,
    ACTIONS(205), 11,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      sym_str_lit,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [837] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 5,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_record,
      anon_sym_templ,
    ACTIONS(209), 11,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      sym_str_lit,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [861] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 5,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_record,
      anon_sym_templ,
    ACTIONS(213), 11,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      sym_str_lit,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [885] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 5,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_record,
      anon_sym_templ,
    ACTIONS(217), 11,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      sym_str_lit,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [909] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 4,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_end,
    ACTIONS(205), 12,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      sym_str_lit,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [933] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 5,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_record,
      anon_sym_templ,
    ACTIONS(221), 11,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      sym_str_lit,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [957] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 5,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_record,
      anon_sym_templ,
    ACTIONS(225), 11,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      sym_str_lit,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [981] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 1,
      anon_sym_DOT,
    ACTIONS(229), 1,
      anon_sym_EQ,
    ACTIONS(193), 3,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(195), 11,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      sym_str_lit,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RBRACK,
  [1009] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 5,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_record,
      anon_sym_templ,
    ACTIONS(231), 11,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      sym_str_lit,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [1033] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 4,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_end,
    ACTIONS(237), 12,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      sym_str_lit,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1057] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 1,
      sym_ident,
    ACTIONS(243), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(46), 2,
      sym_attr,
      aux_sym_attrs_repeat1,
    ACTIONS(241), 11,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      sym_str_lit,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RBRACK,
  [1085] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 5,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_record,
      anon_sym_templ,
    ACTIONS(245), 11,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      sym_str_lit,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [1109] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 5,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_record,
      anon_sym_templ,
    ACTIONS(249), 11,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      sym_str_lit,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [1133] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 4,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_end,
    ACTIONS(201), 12,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      sym_str_lit,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1157] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 4,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_end,
    ACTIONS(245), 12,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      sym_str_lit,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1181] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 4,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_end,
    ACTIONS(231), 12,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      sym_str_lit,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1205] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 4,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_end,
    ACTIONS(225), 12,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      sym_str_lit,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1229] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 5,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_record,
      anon_sym_templ,
    ACTIONS(237), 11,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      sym_str_lit,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [1253] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 4,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_end,
    ACTIONS(209), 12,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      sym_str_lit,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1277] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(253), 4,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_end,
    ACTIONS(255), 12,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      sym_str_lit,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1301] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 1,
      sym_ident,
    ACTIONS(262), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(46), 2,
      sym_attr,
      aux_sym_attrs_repeat1,
    ACTIONS(260), 11,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      sym_str_lit,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RBRACK,
  [1329] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 4,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_end,
    ACTIONS(217), 12,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      sym_str_lit,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1353] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 4,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_end,
    ACTIONS(213), 12,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      sym_str_lit,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1377] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(266), 5,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_record,
      anon_sym_templ,
    ACTIONS(264), 11,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      sym_str_lit,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [1401] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 5,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_record,
      anon_sym_templ,
    ACTIONS(268), 11,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      sym_str_lit,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [1425] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(274), 5,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_record,
      anon_sym_templ,
    ACTIONS(272), 11,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      sym_str_lit,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [1449] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(253), 5,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_record,
      anon_sym_templ,
    ACTIONS(255), 11,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      sym_str_lit,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [1473] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(276), 3,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(278), 11,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      sym_str_lit,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RBRACK,
  [1495] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(280), 3,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(282), 11,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      sym_str_lit,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [1517] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(284), 3,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(286), 11,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      sym_str_lit,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RBRACK,
  [1539] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(288), 1,
      sym_ident,
    ACTIONS(290), 1,
      anon_sym_LBRACK_RBRACK,
    STATE(83), 2,
      sym__type,
      sym_slice_lit,
  [1553] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(292), 1,
      sym_ident,
    ACTIONS(295), 1,
      anon_sym_end,
    STATE(57), 2,
      sym_field,
      aux_sym_fields_repeat1,
  [1567] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(297), 1,
      sym_ident,
    STATE(73), 1,
      sym_fields,
    STATE(59), 2,
      sym_field,
      aux_sym_fields_repeat1,
  [1581] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(299), 1,
      sym_ident,
    ACTIONS(301), 1,
      anon_sym_end,
    STATE(57), 2,
      sym_field,
      aux_sym_fields_repeat1,
  [1595] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(303), 1,
      anon_sym_end,
    ACTIONS(305), 1,
      anon_sym_do,
    STATE(72), 1,
      sym__record_body,
  [1608] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      anon_sym_COLON,
    ACTIONS(307), 1,
      sym_ident,
    STATE(6), 1,
      sym_kwd_lit,
  [1621] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      anon_sym_COLON,
    ACTIONS(309), 1,
      sym_ident,
    STATE(7), 1,
      sym_kwd_lit,
  [1634] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(311), 1,
      anon_sym_end,
    ACTIONS(313), 1,
      anon_sym_do,
    STATE(71), 1,
      sym__templ_body,
  [1647] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(315), 2,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [1655] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(317), 2,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [1663] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(319), 2,
      sym_ident,
      anon_sym_end,
  [1671] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(229), 1,
      anon_sym_EQ,
  [1678] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(321), 1,
      sym_ident,
  [1685] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(323), 1,
      sym_ident,
  [1692] = 2,
    ACTIONS(325), 1,
      sym_comment,
    ACTIONS(327), 1,
      aux_sym_attr_token1,
  [1699] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(329), 1,
      anon_sym_end,
  [1706] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(331), 1,
      anon_sym_end,
  [1713] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(333), 1,
      anon_sym_end,
  [1720] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(335), 1,
      sym_ident,
  [1727] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(337), 1,
      sym_ident,
  [1734] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(339), 1,
      ts_builtin_sym_end,
  [1741] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(341), 1,
      sym_ident,
  [1748] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(343), 1,
      sym_ident,
  [1755] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(345), 1,
      anon_sym_SEMI,
  [1762] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(347), 1,
      anon_sym_SEMI,
  [1769] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(349), 1,
      sym_ident,
  [1776] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(351), 1,
      sym_ident,
  [1783] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(353), 1,
      anon_sym_SEMI,
  [1790] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(355), 1,
      sym_ident,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(8)] = 0,
  [SMALL_STATE(9)] = 48,
  [SMALL_STATE(10)] = 98,
  [SMALL_STATE(11)] = 146,
  [SMALL_STATE(12)] = 196,
  [SMALL_STATE(13)] = 246,
  [SMALL_STATE(14)] = 296,
  [SMALL_STATE(15)] = 346,
  [SMALL_STATE(16)] = 396,
  [SMALL_STATE(17)] = 446,
  [SMALL_STATE(18)] = 496,
  [SMALL_STATE(19)] = 546,
  [SMALL_STATE(20)] = 596,
  [SMALL_STATE(21)] = 643,
  [SMALL_STATE(22)] = 690,
  [SMALL_STATE(23)] = 735,
  [SMALL_STATE(24)] = 762,
  [SMALL_STATE(25)] = 789,
  [SMALL_STATE(26)] = 813,
  [SMALL_STATE(27)] = 837,
  [SMALL_STATE(28)] = 861,
  [SMALL_STATE(29)] = 885,
  [SMALL_STATE(30)] = 909,
  [SMALL_STATE(31)] = 933,
  [SMALL_STATE(32)] = 957,
  [SMALL_STATE(33)] = 981,
  [SMALL_STATE(34)] = 1009,
  [SMALL_STATE(35)] = 1033,
  [SMALL_STATE(36)] = 1057,
  [SMALL_STATE(37)] = 1085,
  [SMALL_STATE(38)] = 1109,
  [SMALL_STATE(39)] = 1133,
  [SMALL_STATE(40)] = 1157,
  [SMALL_STATE(41)] = 1181,
  [SMALL_STATE(42)] = 1205,
  [SMALL_STATE(43)] = 1229,
  [SMALL_STATE(44)] = 1253,
  [SMALL_STATE(45)] = 1277,
  [SMALL_STATE(46)] = 1301,
  [SMALL_STATE(47)] = 1329,
  [SMALL_STATE(48)] = 1353,
  [SMALL_STATE(49)] = 1377,
  [SMALL_STATE(50)] = 1401,
  [SMALL_STATE(51)] = 1425,
  [SMALL_STATE(52)] = 1449,
  [SMALL_STATE(53)] = 1473,
  [SMALL_STATE(54)] = 1495,
  [SMALL_STATE(55)] = 1517,
  [SMALL_STATE(56)] = 1539,
  [SMALL_STATE(57)] = 1553,
  [SMALL_STATE(58)] = 1567,
  [SMALL_STATE(59)] = 1581,
  [SMALL_STATE(60)] = 1595,
  [SMALL_STATE(61)] = 1608,
  [SMALL_STATE(62)] = 1621,
  [SMALL_STATE(63)] = 1634,
  [SMALL_STATE(64)] = 1647,
  [SMALL_STATE(65)] = 1655,
  [SMALL_STATE(66)] = 1663,
  [SMALL_STATE(67)] = 1671,
  [SMALL_STATE(68)] = 1678,
  [SMALL_STATE(69)] = 1685,
  [SMALL_STATE(70)] = 1692,
  [SMALL_STATE(71)] = 1699,
  [SMALL_STATE(72)] = 1706,
  [SMALL_STATE(73)] = 1713,
  [SMALL_STATE(74)] = 1720,
  [SMALL_STATE(75)] = 1727,
  [SMALL_STATE(76)] = 1734,
  [SMALL_STATE(77)] = 1741,
  [SMALL_STATE(78)] = 1748,
  [SMALL_STATE(79)] = 1755,
  [SMALL_STATE(80)] = 1762,
  [SMALL_STATE(81)] = 1769,
  [SMALL_STATE(82)] = 1776,
  [SMALL_STATE(83)] = 1783,
  [SMALL_STATE(84)] = 1790,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 2, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(81),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(64),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [63] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__templ_body, 2, 0, 11),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [99] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__templ_body_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [102] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__templ_body_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [105] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__templ_body_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [108] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__templ_body_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [111] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__templ_body_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [114] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__templ_body_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [117] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__templ_body_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [120] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__templ_body_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__templ_body_repeat1, 2, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [127] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__elements, 2, 0, 0), SHIFT_REPEAT(23),
  [130] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__elements, 2, 0, 0), SHIFT_REPEAT(48),
  [133] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__elements, 2, 0, 0), SHIFT_REPEAT(55),
  [136] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__elements, 2, 0, 0), SHIFT_REPEAT(47),
  [139] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__elements, 2, 0, 0), SHIFT_REPEAT(75),
  [142] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__elements, 2, 0, 0), SHIFT_REPEAT(65),
  [145] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__elements, 2, 0, 0), SHIFT_REPEAT(61),
  [148] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__elements, 2, 0, 0), SHIFT_REPEAT(21),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__elements, 2, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [165] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_list_lit_repeat1, 2, 0, 7), SHIFT_REPEAT(23),
  [168] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_lit_repeat1, 2, 0, 7), SHIFT_REPEAT(48),
  [171] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_lit_repeat1, 2, 0, 7), SHIFT_REPEAT(54),
  [174] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_list_lit_repeat1, 2, 0, 7), SHIFT_REPEAT(47),
  [177] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_lit_repeat1, 2, 0, 7), SHIFT_REPEAT(75),
  [180] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_lit_repeat1, 2, 0, 7), SHIFT_REPEAT(65),
  [183] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_lit_repeat1, 2, 0, 7), SHIFT_REPEAT(61),
  [186] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_lit_repeat1, 2, 0, 7), SHIFT_REPEAT(21),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_lit_repeat1, 2, 0, 7),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expr, 1, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr, 1, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 4, 0, 9),
  [203] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 4, 0, 9),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 5, 0, 15),
  [207] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 5, 0, 15),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_escape, 2, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_escape, 2, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sym, 1, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sym, 1, 0, 0),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bool_lit, 1, 0, 0),
  [219] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bool_lit, 1, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_namespace, 3, 0, 3),
  [223] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_namespace, 3, 0, 3),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_access, 3, 0, 4),
  [227] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field_access, 3, 0, 4),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 3, 0, 5),
  [233] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 3, 0, 5),
  [235] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 4, 0, 10),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 4, 0, 10),
  [239] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attrs, 1, 0, 0),
  [243] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attrs, 1, 0, 0),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_lit, 3, 0, 6),
  [247] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list_lit, 3, 0, 6),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def_record, 3, 0, 8),
  [251] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_def_record, 3, 0, 8),
  [253] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_kwd_lit, 2, 0, 1),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_kwd_lit, 2, 0, 1),
  [257] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_attrs_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_attrs_repeat1, 2, 0, 0),
  [262] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_attrs_repeat1, 2, 0, 0),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def_templ, 5, 0, 16),
  [266] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_def_templ, 5, 0, 16),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def_record, 4, 0, 12),
  [270] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_def_record, 4, 0, 12),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def_templ, 4, 0, 13),
  [274] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_def_templ, 4, 0, 13),
  [276] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attr, 3, 0, 14),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attr, 3, 0, 14),
  [280] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_list_lit_repeat1, 1, 0, 2),
  [282] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_lit_repeat1, 1, 0, 2),
  [284] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__elements, 1, 0, 0),
  [286] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__elements, 1, 0, 0),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [292] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fields_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [295] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_fields_repeat1, 2, 0, 0),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [299] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [301] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fields, 1, 0, 0),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [319] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field, 3, 0, 17),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [325] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [327] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [333] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__record_body, 2, 0, 11),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [339] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [345] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slice_lit, 2, 0, 1),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_tel(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_ident,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
