#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 100
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 63
#define ALIAS_COUNT 0
#define TOKEN_COUNT 32
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 12
#define MAX_ALIAS_SEQUENCE_LENGTH 10
#define PRODUCTION_ID_COUNT 10

enum ts_symbol_identifiers {
  sym_ident = 1,
  sym_comment = 2,
  aux_sym_escape_char_token1 = 3,
  aux_sym_escape_char_token2 = 4,
  anon_sym_namespace = 5,
  anon_sym_SEMI = 6,
  anon_sym_LBRACK_RBRACK = 7,
  anon_sym_record = 8,
  anon_sym_do = 9,
  anon_sym_end = 10,
  anon_sym_templ = 11,
  anon_sym_LPAREN = 12,
  anon_sym_RPAREN = 13,
  anon_sym_PLUS = 14,
  anon_sym_DASH = 15,
  anon_sym_STAR = 16,
  anon_sym_SLASH = 17,
  sym_literal_int = 18,
  sym_literal_str = 19,
  anon_sym_true = 20,
  anon_sym_false = 21,
  anon_sym_DOT = 22,
  anon_sym_COLON = 23,
  anon_sym_foreach = 24,
  anon_sym_COMMA = 25,
  anon_sym_in = 26,
  anon_sym_LBRACK = 27,
  anon_sym_RBRACK = 28,
  aux_sym_element_token1 = 29,
  anon_sym_EQ = 30,
  aux_sym_attr_token1 = 31,
  sym_source = 32,
  sym__toplevel_stmt = 33,
  sym__stmt = 34,
  sym_escape_char = 35,
  sym_record_components = 36,
  sym_namespace = 37,
  sym_record_component = 38,
  sym__type = 39,
  sym_slice_type = 40,
  sym_def_record = 41,
  sym_def_templ = 42,
  sym_templ_body = 43,
  sym_expr = 44,
  sym__basic_expr = 45,
  sym__control_expr = 46,
  sym__operation = 47,
  sym_operator = 48,
  sym_literal_bool = 49,
  sym_field_access = 50,
  sym_foreach = 51,
  sym_foreach_body = 52,
  sym_element = 53,
  sym_elements = 54,
  sym_attrs = 55,
  sym_attr = 56,
  aux_sym_source_repeat1 = 57,
  aux_sym_record_components_repeat1 = 58,
  aux_sym_templ_body_repeat1 = 59,
  aux_sym__operation_repeat1 = 60,
  aux_sym_foreach_body_repeat1 = 61,
  aux_sym_attrs_repeat1 = 62,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_ident] = "ident",
  [sym_comment] = "comment",
  [aux_sym_escape_char_token1] = "escape_char_token1",
  [aux_sym_escape_char_token2] = "escape_char_token2",
  [anon_sym_namespace] = "namespace",
  [anon_sym_SEMI] = ";",
  [anon_sym_LBRACK_RBRACK] = "[]",
  [anon_sym_record] = "record",
  [anon_sym_do] = "do",
  [anon_sym_end] = "end",
  [anon_sym_templ] = "templ",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [sym_literal_int] = "literal_int",
  [sym_literal_str] = "literal_str",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_DOT] = ".",
  [anon_sym_COLON] = ":",
  [anon_sym_foreach] = "foreach",
  [anon_sym_COMMA] = ",",
  [anon_sym_in] = "in",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [aux_sym_element_token1] = "element_token1",
  [anon_sym_EQ] = "=",
  [aux_sym_attr_token1] = "text",
  [sym_source] = "source",
  [sym__toplevel_stmt] = "_toplevel_stmt",
  [sym__stmt] = "_stmt",
  [sym_escape_char] = "escape_char",
  [sym_record_components] = "components",
  [sym_namespace] = "namespace",
  [sym_record_component] = "component",
  [sym__type] = "_type",
  [sym_slice_type] = "slice",
  [sym_def_record] = "def_record",
  [sym_def_templ] = "def_templ",
  [sym_templ_body] = "body",
  [sym_expr] = "expr",
  [sym__basic_expr] = "_basic_expr",
  [sym__control_expr] = "_control_expr",
  [sym__operation] = "_operation",
  [sym_operator] = "operator",
  [sym_literal_bool] = "literal_bool",
  [sym_field_access] = "field_access",
  [sym_foreach] = "foreach",
  [sym_foreach_body] = "body",
  [sym_element] = "element",
  [sym_elements] = "elements",
  [sym_attrs] = "attrs",
  [sym_attr] = "attr",
  [aux_sym_source_repeat1] = "source_repeat1",
  [aux_sym_record_components_repeat1] = "record_components_repeat1",
  [aux_sym_templ_body_repeat1] = "templ_body_repeat1",
  [aux_sym__operation_repeat1] = "_operation_repeat1",
  [aux_sym_foreach_body_repeat1] = "foreach_body_repeat1",
  [aux_sym_attrs_repeat1] = "attrs_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_ident] = sym_ident,
  [sym_comment] = sym_comment,
  [aux_sym_escape_char_token1] = aux_sym_escape_char_token1,
  [aux_sym_escape_char_token2] = aux_sym_escape_char_token2,
  [anon_sym_namespace] = anon_sym_namespace,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LBRACK_RBRACK] = anon_sym_LBRACK_RBRACK,
  [anon_sym_record] = anon_sym_record,
  [anon_sym_do] = anon_sym_do,
  [anon_sym_end] = anon_sym_end,
  [anon_sym_templ] = anon_sym_templ,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [sym_literal_int] = sym_literal_int,
  [sym_literal_str] = sym_literal_str,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_foreach] = anon_sym_foreach,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [aux_sym_element_token1] = aux_sym_element_token1,
  [anon_sym_EQ] = anon_sym_EQ,
  [aux_sym_attr_token1] = aux_sym_attr_token1,
  [sym_source] = sym_source,
  [sym__toplevel_stmt] = sym__toplevel_stmt,
  [sym__stmt] = sym__stmt,
  [sym_escape_char] = sym_escape_char,
  [sym_record_components] = sym_record_components,
  [sym_namespace] = sym_namespace,
  [sym_record_component] = sym_record_component,
  [sym__type] = sym__type,
  [sym_slice_type] = sym_slice_type,
  [sym_def_record] = sym_def_record,
  [sym_def_templ] = sym_def_templ,
  [sym_templ_body] = sym_templ_body,
  [sym_expr] = sym_expr,
  [sym__basic_expr] = sym__basic_expr,
  [sym__control_expr] = sym__control_expr,
  [sym__operation] = sym__operation,
  [sym_operator] = sym_operator,
  [sym_literal_bool] = sym_literal_bool,
  [sym_field_access] = sym_field_access,
  [sym_foreach] = sym_foreach,
  [sym_foreach_body] = sym_templ_body,
  [sym_element] = sym_element,
  [sym_elements] = sym_elements,
  [sym_attrs] = sym_attrs,
  [sym_attr] = sym_attr,
  [aux_sym_source_repeat1] = aux_sym_source_repeat1,
  [aux_sym_record_components_repeat1] = aux_sym_record_components_repeat1,
  [aux_sym_templ_body_repeat1] = aux_sym_templ_body_repeat1,
  [aux_sym__operation_repeat1] = aux_sym__operation_repeat1,
  [aux_sym_foreach_body_repeat1] = aux_sym_foreach_body_repeat1,
  [aux_sym_attrs_repeat1] = aux_sym_attrs_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_escape_char_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_escape_char_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_namespace] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_record] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_do] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_end] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_templ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_literal_int] = {
    .visible = true,
    .named = true,
  },
  [sym_literal_str] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_foreach] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_element_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_attr_token1] = {
    .visible = true,
    .named = true,
  },
  [sym_source] = {
    .visible = true,
    .named = true,
  },
  [sym__toplevel_stmt] = {
    .visible = false,
    .named = true,
  },
  [sym__stmt] = {
    .visible = false,
    .named = true,
  },
  [sym_escape_char] = {
    .visible = true,
    .named = true,
  },
  [sym_record_components] = {
    .visible = true,
    .named = true,
  },
  [sym_namespace] = {
    .visible = true,
    .named = true,
  },
  [sym_record_component] = {
    .visible = true,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym_slice_type] = {
    .visible = true,
    .named = true,
  },
  [sym_def_record] = {
    .visible = true,
    .named = true,
  },
  [sym_def_templ] = {
    .visible = true,
    .named = true,
  },
  [sym_templ_body] = {
    .visible = true,
    .named = true,
  },
  [sym_expr] = {
    .visible = true,
    .named = true,
  },
  [sym__basic_expr] = {
    .visible = false,
    .named = true,
  },
  [sym__control_expr] = {
    .visible = false,
    .named = true,
  },
  [sym__operation] = {
    .visible = false,
    .named = true,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_literal_bool] = {
    .visible = true,
    .named = true,
  },
  [sym_field_access] = {
    .visible = true,
    .named = true,
  },
  [sym_foreach] = {
    .visible = true,
    .named = true,
  },
  [sym_foreach_body] = {
    .visible = true,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym_elements] = {
    .visible = true,
    .named = true,
  },
  [sym_attrs] = {
    .visible = true,
    .named = true,
  },
  [sym_attr] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_record_components_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_templ_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__operation_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_foreach_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_attrs_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_field = 1,
  field_index = 2,
  field_item = 3,
  field_iter = 4,
  field_key = 5,
  field_keyword = 6,
  field_name = 7,
  field_object = 8,
  field_tag = 9,
  field_type = 10,
  field_val = 11,
  field_var = 12,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_field] = "field",
  [field_index] = "index",
  [field_item] = "item",
  [field_iter] = "iter",
  [field_key] = "key",
  [field_keyword] = "keyword",
  [field_name] = "name",
  [field_object] = "object",
  [field_tag] = "tag",
  [field_type] = "type",
  [field_val] = "val",
  [field_var] = "var",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 0, .length = 1},
  [3] = {.index = 1, .length = 1},
  [4] = {.index = 2, .length = 1},
  [5] = {.index = 3, .length = 2},
  [6] = {.index = 5, .length = 2},
  [7] = {.index = 7, .length = 2},
  [8] = {.index = 9, .length = 2},
  [9] = {.index = 11, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_tag, 1},
  [2] =
    {field_keyword, 1},
  [3] =
    {field_type, 2},
    {field_var, 1},
  [5] =
    {field_field, 2},
    {field_object, 0},
  [7] =
    {field_key, 0},
    {field_val, 2},
  [9] =
    {field_name, 0},
    {field_type, 1},
  [11] =
    {field_index, 3},
    {field_item, 5},
    {field_iter, 7},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [1] = sym_ident,
  },
  [5] = {
    [1] = sym_ident,
    [2] = sym_ident,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 5,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 6,
  [12] = 12,
  [13] = 13,
  [14] = 13,
  [15] = 12,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 16,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 22,
  [42] = 28,
  [43] = 25,
  [44] = 26,
  [45] = 23,
  [46] = 33,
  [47] = 21,
  [48] = 48,
  [49] = 30,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 83,
  [89] = 89,
  [90] = 90,
  [91] = 68,
  [92] = 92,
  [93] = 64,
  [94] = 94,
  [95] = 77,
  [96] = 69,
  [97] = 97,
  [98] = 92,
  [99] = 90,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      ADVANCE_MAP(
        '"', 1,
        '#', 14,
        '\'', 3,
        '(', 21,
        ')', 22,
        '*', 25,
        '+', 23,
        ',', 32,
        '-', 24,
        '.', 30,
        '/', 26,
        '0', 27,
        ':', 31,
        ';', 19,
        '=', 37,
        '[', 34,
        '\\', 4,
        ']', 35,
        '_', 10,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(13);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(29);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(14);
      if (lookahead == '[') ADVANCE(5);
      if (lookahead == '_') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(13);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(29);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '(') ADVANCE(18);
      if (lookahead == '[') ADVANCE(17);
      END_STATE();
    case 5:
      if (lookahead == ']') ADVANCE(20);
      END_STATE();
    case 6:
      if (eof) ADVANCE(8);
      ADVANCE_MAP(
        '"', 1,
        '#', 14,
        '\'', 3,
        '(', 21,
        ')', 22,
        '*', 25,
        '+', 23,
        ',', 32,
        '-', 24,
        '.', 30,
        '/', 26,
        '0', 27,
        ':', 31,
        ';', 19,
        '[', 34,
        '\\', 4,
        ']', 35,
        '_', 10,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(13);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 7:
      if (eof) ADVANCE(8);
      if (lookahead == '#') ADVANCE(14);
      if (lookahead == '(') ADVANCE(21);
      if (lookahead == ')') ADVANCE(22);
      if (lookahead == '[') ADVANCE(33);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead == ']') ADVANCE(35);
      if (lookahead == '_') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(13);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '-') ADVANCE(11);
      if (lookahead == '_') ADVANCE(12);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(13);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '_') ADVANCE(12);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(13);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '-' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_ident);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '#') ADVANCE(14);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '#') ADVANCE(15);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == ']') ADVANCE(14);
      if (lookahead != 0) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '#') ADVANCE(14);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_escape_char_token1);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_escape_char_token2);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LBRACK_RBRACK);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_literal_int);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_literal_int);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_literal_str);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      if (lookahead == ':') ADVANCE(36);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      if (lookahead == ':') ADVANCE(36);
      if (lookahead == ']') ADVANCE(20);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_element_token1);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_attr_token1);
      if (lookahead == '#') ADVANCE(15);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ']') ADVANCE(39);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_attr_token1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ']') ADVANCE(39);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'd') ADVANCE(1);
      if (lookahead == 'e') ADVANCE(2);
      if (lookahead == 'f') ADVANCE(3);
      if (lookahead == 'i') ADVANCE(4);
      if (lookahead == 'n') ADVANCE(5);
      if (lookahead == 'r') ADVANCE(6);
      if (lookahead == 't') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'o') ADVANCE(8);
      END_STATE();
    case 2:
      if (lookahead == 'n') ADVANCE(9);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(10);
      if (lookahead == 'o') ADVANCE(11);
      END_STATE();
    case 4:
      if (lookahead == 'n') ADVANCE(12);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(13);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(14);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(15);
      if (lookahead == 'r') ADVANCE(16);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_do);
      END_STATE();
    case 9:
      if (lookahead == 'd') ADVANCE(17);
      END_STATE();
    case 10:
      if (lookahead == 'l') ADVANCE(18);
      END_STATE();
    case 11:
      if (lookahead == 'r') ADVANCE(19);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 13:
      if (lookahead == 'm') ADVANCE(20);
      END_STATE();
    case 14:
      if (lookahead == 'c') ADVANCE(21);
      END_STATE();
    case 15:
      if (lookahead == 'm') ADVANCE(22);
      END_STATE();
    case 16:
      if (lookahead == 'u') ADVANCE(23);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_end);
      END_STATE();
    case 18:
      if (lookahead == 's') ADVANCE(24);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(25);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(26);
      END_STATE();
    case 21:
      if (lookahead == 'o') ADVANCE(27);
      END_STATE();
    case 22:
      if (lookahead == 'p') ADVANCE(28);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(29);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(30);
      END_STATE();
    case 25:
      if (lookahead == 'a') ADVANCE(31);
      END_STATE();
    case 26:
      if (lookahead == 's') ADVANCE(32);
      END_STATE();
    case 27:
      if (lookahead == 'r') ADVANCE(33);
      END_STATE();
    case 28:
      if (lookahead == 'l') ADVANCE(34);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 31:
      if (lookahead == 'c') ADVANCE(35);
      END_STATE();
    case 32:
      if (lookahead == 'p') ADVANCE(36);
      END_STATE();
    case 33:
      if (lookahead == 'd') ADVANCE(37);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_templ);
      END_STATE();
    case 35:
      if (lookahead == 'h') ADVANCE(38);
      END_STATE();
    case 36:
      if (lookahead == 'a') ADVANCE(39);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_record);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_foreach);
      END_STATE();
    case 39:
      if (lookahead == 'c') ADVANCE(40);
      END_STATE();
    case 40:
      if (lookahead == 'e') ADVANCE(41);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_namespace);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 7},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 7},
  [5] = {.lex_state = 7},
  [6] = {.lex_state = 7},
  [7] = {.lex_state = 7},
  [8] = {.lex_state = 7},
  [9] = {.lex_state = 7},
  [10] = {.lex_state = 7},
  [11] = {.lex_state = 7},
  [12] = {.lex_state = 7},
  [13] = {.lex_state = 7},
  [14] = {.lex_state = 7},
  [15] = {.lex_state = 7},
  [16] = {.lex_state = 7},
  [17] = {.lex_state = 7},
  [18] = {.lex_state = 7},
  [19] = {.lex_state = 7},
  [20] = {.lex_state = 7},
  [21] = {.lex_state = 7},
  [22] = {.lex_state = 7},
  [23] = {.lex_state = 7},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 7},
  [26] = {.lex_state = 7},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 7},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 7},
  [31] = {.lex_state = 7},
  [32] = {.lex_state = 7},
  [33] = {.lex_state = 7},
  [34] = {.lex_state = 7},
  [35] = {.lex_state = 7},
  [36] = {.lex_state = 7},
  [37] = {.lex_state = 7},
  [38] = {.lex_state = 7},
  [39] = {.lex_state = 7},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 7},
  [42] = {.lex_state = 7},
  [43] = {.lex_state = 7},
  [44] = {.lex_state = 7},
  [45] = {.lex_state = 7},
  [46] = {.lex_state = 7},
  [47] = {.lex_state = 7},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 7},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 7},
  [52] = {.lex_state = 7},
  [53] = {.lex_state = 7},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 2},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 38},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_ident] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [aux_sym_escape_char_token1] = ACTIONS(1),
    [aux_sym_escape_char_token2] = ACTIONS(1),
    [anon_sym_namespace] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LBRACK_RBRACK] = ACTIONS(1),
    [anon_sym_record] = ACTIONS(1),
    [anon_sym_do] = ACTIONS(1),
    [anon_sym_end] = ACTIONS(1),
    [anon_sym_templ] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [sym_literal_int] = ACTIONS(1),
    [sym_literal_str] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_foreach] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [aux_sym_element_token1] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
  },
  [1] = {
    [sym_source] = STATE(89),
    [sym__toplevel_stmt] = STATE(9),
    [sym__stmt] = STATE(9),
    [sym_escape_char] = STATE(9),
    [sym_namespace] = STATE(8),
    [sym_def_record] = STATE(9),
    [sym_def_templ] = STATE(9),
    [sym_expr] = STATE(9),
    [sym_element] = STATE(9),
    [aux_sym_source_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
    [aux_sym_escape_char_token1] = ACTIONS(7),
    [aux_sym_escape_char_token2] = ACTIONS(7),
    [anon_sym_namespace] = ACTIONS(9),
    [anon_sym_record] = ACTIONS(11),
    [anon_sym_templ] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(17),
    [aux_sym_element_token1] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      sym_ident,
    ACTIONS(29), 1,
      anon_sym_COLON,
    STATE(29), 1,
      sym_operator,
    ACTIONS(25), 2,
      sym_literal_int,
      sym_literal_str,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(23), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(83), 6,
      sym__basic_expr,
      sym__control_expr,
      sym__operation,
      sym_literal_bool,
      sym_field_access,
      sym_foreach,
  [35] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      sym_ident,
    ACTIONS(29), 1,
      anon_sym_COLON,
    STATE(29), 1,
      sym_operator,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(31), 2,
      sym_literal_int,
      sym_literal_str,
    ACTIONS(23), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(88), 6,
      sym__basic_expr,
      sym__control_expr,
      sym__operation,
      sym_literal_bool,
      sym_field_access,
      sym_foreach,
  [70] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    ACTIONS(38), 1,
      anon_sym_record,
    ACTIONS(41), 1,
      anon_sym_templ,
    ACTIONS(44), 1,
      anon_sym_LPAREN,
    ACTIONS(47), 1,
      anon_sym_LBRACK,
    ACTIONS(50), 1,
      aux_sym_element_token1,
    ACTIONS(35), 2,
      aux_sym_escape_char_token1,
      aux_sym_escape_char_token2,
    STATE(4), 8,
      sym__toplevel_stmt,
      sym__stmt,
      sym_escape_char,
      sym_def_record,
      sym_def_templ,
      sym_expr,
      sym_element,
      aux_sym_source_repeat1,
  [106] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      aux_sym_element_token1,
    ACTIONS(53), 1,
      sym_ident,
    ACTIONS(55), 1,
      anon_sym_RBRACK,
    STATE(15), 1,
      sym_attrs,
    STATE(68), 1,
      sym_elements,
    ACTIONS(7), 2,
      aux_sym_escape_char_token1,
      aux_sym_escape_char_token2,
    STATE(31), 2,
      sym_attr,
      aux_sym_attrs_repeat1,
    STATE(19), 5,
      sym__stmt,
      sym_escape_char,
      sym_expr,
      sym_element,
      aux_sym_templ_body_repeat1,
  [146] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      aux_sym_element_token1,
    ACTIONS(53), 1,
      sym_ident,
    ACTIONS(57), 1,
      anon_sym_RBRACK,
    STATE(13), 1,
      sym_attrs,
    STATE(93), 1,
      sym_elements,
    ACTIONS(7), 2,
      aux_sym_escape_char_token1,
      aux_sym_escape_char_token2,
    STATE(31), 2,
      sym_attr,
      aux_sym_attrs_repeat1,
    STATE(19), 5,
      sym__stmt,
      sym_escape_char,
      sym_expr,
      sym_element,
      aux_sym_templ_body_repeat1,
  [186] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      aux_sym_element_token1,
    ACTIONS(53), 1,
      sym_ident,
    ACTIONS(59), 1,
      anon_sym_RBRACK,
    STATE(12), 1,
      sym_attrs,
    STATE(91), 1,
      sym_elements,
    ACTIONS(7), 2,
      aux_sym_escape_char_token1,
      aux_sym_escape_char_token2,
    STATE(31), 2,
      sym_attr,
      aux_sym_attrs_repeat1,
    STATE(19), 5,
      sym__stmt,
      sym_escape_char,
      sym_expr,
      sym_element,
      aux_sym_templ_body_repeat1,
  [226] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_record,
    ACTIONS(13), 1,
      anon_sym_templ,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      aux_sym_element_token1,
    ACTIONS(61), 1,
      ts_builtin_sym_end,
    ACTIONS(7), 2,
      aux_sym_escape_char_token1,
      aux_sym_escape_char_token2,
    STATE(10), 8,
      sym__toplevel_stmt,
      sym__stmt,
      sym_escape_char,
      sym_def_record,
      sym_def_templ,
      sym_expr,
      sym_element,
      aux_sym_source_repeat1,
  [262] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_record,
    ACTIONS(13), 1,
      anon_sym_templ,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      aux_sym_element_token1,
    ACTIONS(61), 1,
      ts_builtin_sym_end,
    ACTIONS(7), 2,
      aux_sym_escape_char_token1,
      aux_sym_escape_char_token2,
    STATE(4), 8,
      sym__toplevel_stmt,
      sym__stmt,
      sym_escape_char,
      sym_def_record,
      sym_def_templ,
      sym_expr,
      sym_element,
      aux_sym_source_repeat1,
  [298] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_record,
    ACTIONS(13), 1,
      anon_sym_templ,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      aux_sym_element_token1,
    ACTIONS(63), 1,
      ts_builtin_sym_end,
    ACTIONS(7), 2,
      aux_sym_escape_char_token1,
      aux_sym_escape_char_token2,
    STATE(4), 8,
      sym__toplevel_stmt,
      sym__stmt,
      sym_escape_char,
      sym_def_record,
      sym_def_templ,
      sym_expr,
      sym_element,
      aux_sym_source_repeat1,
  [334] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      aux_sym_element_token1,
    ACTIONS(53), 1,
      sym_ident,
    ACTIONS(65), 1,
      anon_sym_RBRACK,
    STATE(14), 1,
      sym_attrs,
    STATE(64), 1,
      sym_elements,
    ACTIONS(7), 2,
      aux_sym_escape_char_token1,
      aux_sym_escape_char_token2,
    STATE(31), 2,
      sym_attr,
      aux_sym_attrs_repeat1,
    STATE(19), 5,
      sym__stmt,
      sym_escape_char,
      sym_expr,
      sym_element,
      aux_sym_templ_body_repeat1,
  [374] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      aux_sym_element_token1,
    ACTIONS(67), 1,
      anon_sym_RBRACK,
    STATE(95), 1,
      sym_elements,
    ACTIONS(7), 2,
      aux_sym_escape_char_token1,
      aux_sym_escape_char_token2,
    STATE(19), 5,
      sym__stmt,
      sym_escape_char,
      sym_expr,
      sym_element,
      aux_sym_templ_body_repeat1,
  [404] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      aux_sym_element_token1,
    ACTIONS(69), 1,
      anon_sym_RBRACK,
    STATE(96), 1,
      sym_elements,
    ACTIONS(7), 2,
      aux_sym_escape_char_token1,
      aux_sym_escape_char_token2,
    STATE(19), 5,
      sym__stmt,
      sym_escape_char,
      sym_expr,
      sym_element,
      aux_sym_templ_body_repeat1,
  [434] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      aux_sym_element_token1,
    ACTIONS(71), 1,
      anon_sym_RBRACK,
    STATE(69), 1,
      sym_elements,
    ACTIONS(7), 2,
      aux_sym_escape_char_token1,
      aux_sym_escape_char_token2,
    STATE(19), 5,
      sym__stmt,
      sym_escape_char,
      sym_expr,
      sym_element,
      aux_sym_templ_body_repeat1,
  [464] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      aux_sym_element_token1,
    ACTIONS(73), 1,
      anon_sym_RBRACK,
    STATE(77), 1,
      sym_elements,
    ACTIONS(7), 2,
      aux_sym_escape_char_token1,
      aux_sym_escape_char_token2,
    STATE(19), 5,
      sym__stmt,
      sym_escape_char,
      sym_expr,
      sym_element,
      aux_sym_templ_body_repeat1,
  [494] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      anon_sym_end,
    ACTIONS(80), 1,
      anon_sym_LPAREN,
    ACTIONS(83), 1,
      anon_sym_LBRACK,
    ACTIONS(86), 1,
      aux_sym_element_token1,
    ACTIONS(75), 2,
      aux_sym_escape_char_token1,
      aux_sym_escape_char_token2,
    STATE(16), 5,
      sym__stmt,
      sym_escape_char,
      sym_expr,
      sym_element,
      aux_sym_templ_body_repeat1,
  [521] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      anon_sym_end,
    ACTIONS(93), 1,
      anon_sym_LPAREN,
    ACTIONS(95), 1,
      anon_sym_LBRACK,
    ACTIONS(97), 1,
      aux_sym_element_token1,
    ACTIONS(89), 2,
      aux_sym_escape_char_token1,
      aux_sym_escape_char_token2,
    STATE(16), 5,
      sym__stmt,
      sym_escape_char,
      sym_expr,
      sym_element,
      aux_sym_templ_body_repeat1,
  [548] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_LPAREN,
    ACTIONS(95), 1,
      anon_sym_LBRACK,
    ACTIONS(97), 1,
      aux_sym_element_token1,
    STATE(81), 1,
      sym_templ_body,
    ACTIONS(89), 2,
      aux_sym_escape_char_token1,
      aux_sym_escape_char_token2,
    STATE(17), 5,
      sym__stmt,
      sym_escape_char,
      sym_expr,
      sym_element,
      aux_sym_templ_body_repeat1,
  [575] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      aux_sym_element_token1,
    ACTIONS(99), 1,
      anon_sym_RBRACK,
    ACTIONS(7), 2,
      aux_sym_escape_char_token1,
      aux_sym_escape_char_token2,
    STATE(20), 5,
      sym__stmt,
      sym_escape_char,
      sym_expr,
      sym_element,
      aux_sym_templ_body_repeat1,
  [602] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      anon_sym_RBRACK,
    ACTIONS(104), 1,
      anon_sym_LPAREN,
    ACTIONS(107), 1,
      anon_sym_LBRACK,
    ACTIONS(110), 1,
      aux_sym_element_token1,
    ACTIONS(101), 2,
      aux_sym_escape_char_token1,
      aux_sym_escape_char_token2,
    STATE(20), 5,
      sym__stmt,
      sym_escape_char,
      sym_expr,
      sym_element,
      aux_sym_templ_body_repeat1,
  [629] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      anon_sym_LBRACK,
    ACTIONS(113), 9,
      ts_builtin_sym_end,
      aux_sym_escape_char_token1,
      aux_sym_escape_char_token2,
      anon_sym_record,
      anon_sym_templ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      aux_sym_element_token1,
  [647] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 1,
      anon_sym_LBRACK,
    ACTIONS(117), 9,
      ts_builtin_sym_end,
      aux_sym_escape_char_token1,
      aux_sym_escape_char_token2,
      anon_sym_record,
      anon_sym_templ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      aux_sym_element_token1,
  [665] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      anon_sym_LBRACK,
    ACTIONS(121), 9,
      ts_builtin_sym_end,
      aux_sym_escape_char_token1,
      aux_sym_escape_char_token2,
      anon_sym_record,
      anon_sym_templ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      aux_sym_element_token1,
  [683] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      sym_ident,
    ACTIONS(128), 1,
      anon_sym_RPAREN,
    ACTIONS(130), 2,
      sym_literal_int,
      sym_literal_str,
    ACTIONS(133), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(24), 4,
      sym__basic_expr,
      sym_literal_bool,
      sym_field_access,
      aux_sym__operation_repeat1,
  [707] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 1,
      anon_sym_LBRACK,
    ACTIONS(136), 9,
      ts_builtin_sym_end,
      aux_sym_escape_char_token1,
      aux_sym_escape_char_token2,
      anon_sym_record,
      anon_sym_templ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      aux_sym_element_token1,
  [725] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 1,
      anon_sym_LBRACK,
    ACTIONS(140), 9,
      ts_builtin_sym_end,
      aux_sym_escape_char_token1,
      aux_sym_escape_char_token2,
      anon_sym_record,
      anon_sym_templ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      aux_sym_element_token1,
  [743] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      sym_ident,
    ACTIONS(144), 1,
      anon_sym_RPAREN,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(146), 2,
      sym_literal_int,
      sym_literal_str,
    STATE(24), 4,
      sym__basic_expr,
      sym_literal_bool,
      sym_field_access,
      aux_sym__operation_repeat1,
  [767] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 1,
      anon_sym_LBRACK,
    ACTIONS(148), 9,
      ts_builtin_sym_end,
      aux_sym_escape_char_token1,
      aux_sym_escape_char_token2,
      anon_sym_record,
      anon_sym_templ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      aux_sym_element_token1,
  [785] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      sym_ident,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(152), 2,
      sym_literal_int,
      sym_literal_str,
    STATE(27), 4,
      sym__basic_expr,
      sym_literal_bool,
      sym_field_access,
      aux_sym__operation_repeat1,
  [806] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 1,
      anon_sym_LBRACK,
    ACTIONS(154), 8,
      ts_builtin_sym_end,
      aux_sym_escape_char_token1,
      aux_sym_escape_char_token2,
      anon_sym_record,
      anon_sym_templ,
      anon_sym_LPAREN,
      anon_sym_RBRACK,
      aux_sym_element_token1,
  [823] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      sym_ident,
    ACTIONS(160), 1,
      anon_sym_LBRACK,
    STATE(32), 2,
      sym_attr,
      aux_sym_attrs_repeat1,
    ACTIONS(158), 5,
      aux_sym_escape_char_token1,
      aux_sym_escape_char_token2,
      anon_sym_LPAREN,
      anon_sym_RBRACK,
      aux_sym_element_token1,
  [844] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(162), 1,
      sym_ident,
    ACTIONS(167), 1,
      anon_sym_LBRACK,
    STATE(32), 2,
      sym_attr,
      aux_sym_attrs_repeat1,
    ACTIONS(165), 5,
      aux_sym_escape_char_token1,
      aux_sym_escape_char_token2,
      anon_sym_LPAREN,
      anon_sym_RBRACK,
      aux_sym_element_token1,
  [865] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 1,
      anon_sym_LBRACK,
    ACTIONS(169), 8,
      ts_builtin_sym_end,
      aux_sym_escape_char_token1,
      aux_sym_escape_char_token2,
      anon_sym_record,
      anon_sym_templ,
      anon_sym_LPAREN,
      anon_sym_RBRACK,
      aux_sym_element_token1,
  [882] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 1,
      anon_sym_LBRACK,
    ACTIONS(173), 7,
      ts_builtin_sym_end,
      aux_sym_escape_char_token1,
      aux_sym_escape_char_token2,
      anon_sym_record,
      anon_sym_templ,
      anon_sym_LPAREN,
      aux_sym_element_token1,
  [898] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 1,
      anon_sym_LBRACK,
    ACTIONS(177), 7,
      ts_builtin_sym_end,
      aux_sym_escape_char_token1,
      aux_sym_escape_char_token2,
      anon_sym_record,
      anon_sym_templ,
      anon_sym_LPAREN,
      aux_sym_element_token1,
  [914] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 1,
      anon_sym_LBRACK,
    ACTIONS(181), 7,
      ts_builtin_sym_end,
      aux_sym_escape_char_token1,
      aux_sym_escape_char_token2,
      anon_sym_record,
      anon_sym_templ,
      anon_sym_LPAREN,
      aux_sym_element_token1,
  [930] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 1,
      anon_sym_LBRACK,
    ACTIONS(185), 7,
      ts_builtin_sym_end,
      aux_sym_escape_char_token1,
      aux_sym_escape_char_token2,
      anon_sym_record,
      anon_sym_templ,
      anon_sym_LPAREN,
      aux_sym_element_token1,
  [946] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 1,
      anon_sym_LBRACK,
    ACTIONS(189), 7,
      ts_builtin_sym_end,
      aux_sym_escape_char_token1,
      aux_sym_escape_char_token2,
      anon_sym_record,
      anon_sym_templ,
      anon_sym_LPAREN,
      aux_sym_element_token1,
  [962] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 1,
      anon_sym_LBRACK,
    ACTIONS(193), 6,
      sym_ident,
      aux_sym_escape_char_token1,
      aux_sym_escape_char_token2,
      anon_sym_LPAREN,
      anon_sym_RBRACK,
      aux_sym_element_token1,
  [977] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 1,
      anon_sym_DOT,
    ACTIONS(197), 3,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(199), 3,
      anon_sym_RPAREN,
      sym_literal_int,
      sym_literal_str,
  [994] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 1,
      anon_sym_LBRACK,
    ACTIONS(117), 5,
      aux_sym_escape_char_token1,
      aux_sym_escape_char_token2,
      anon_sym_end,
      anon_sym_LPAREN,
      aux_sym_element_token1,
  [1008] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 1,
      anon_sym_LBRACK,
    ACTIONS(148), 5,
      aux_sym_escape_char_token1,
      aux_sym_escape_char_token2,
      anon_sym_end,
      anon_sym_LPAREN,
      aux_sym_element_token1,
  [1022] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 1,
      anon_sym_LBRACK,
    ACTIONS(136), 5,
      aux_sym_escape_char_token1,
      aux_sym_escape_char_token2,
      anon_sym_end,
      anon_sym_LPAREN,
      aux_sym_element_token1,
  [1036] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 1,
      anon_sym_LBRACK,
    ACTIONS(140), 5,
      aux_sym_escape_char_token1,
      aux_sym_escape_char_token2,
      anon_sym_end,
      anon_sym_LPAREN,
      aux_sym_element_token1,
  [1050] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      anon_sym_LBRACK,
    ACTIONS(121), 5,
      aux_sym_escape_char_token1,
      aux_sym_escape_char_token2,
      anon_sym_end,
      anon_sym_LPAREN,
      aux_sym_element_token1,
  [1064] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 1,
      anon_sym_LBRACK,
    ACTIONS(169), 5,
      aux_sym_escape_char_token1,
      aux_sym_escape_char_token2,
      anon_sym_end,
      anon_sym_LPAREN,
      aux_sym_element_token1,
  [1078] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      anon_sym_LBRACK,
    ACTIONS(113), 5,
      aux_sym_escape_char_token1,
      aux_sym_escape_char_token2,
      anon_sym_end,
      anon_sym_LPAREN,
      aux_sym_element_token1,
  [1092] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 3,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(205), 3,
      anon_sym_RPAREN,
      sym_literal_int,
      sym_literal_str,
  [1106] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 1,
      anon_sym_LBRACK,
    ACTIONS(154), 5,
      aux_sym_escape_char_token1,
      aux_sym_escape_char_token2,
      anon_sym_end,
      anon_sym_LPAREN,
      aux_sym_element_token1,
  [1120] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 3,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(209), 3,
      anon_sym_RPAREN,
      sym_literal_int,
      sym_literal_str,
  [1134] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 1,
      anon_sym_RPAREN,
    ACTIONS(213), 1,
      anon_sym_LBRACK,
    ACTIONS(216), 1,
      aux_sym_element_token1,
    STATE(51), 2,
      sym_element,
      aux_sym_foreach_body_repeat1,
  [1151] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      aux_sym_element_token1,
    ACTIONS(219), 1,
      anon_sym_RPAREN,
    STATE(51), 2,
      sym_element,
      aux_sym_foreach_body_repeat1,
  [1168] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      aux_sym_element_token1,
    STATE(76), 1,
      sym_foreach_body,
    STATE(52), 2,
      sym_element,
      aux_sym_foreach_body_repeat1,
  [1185] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 2,
      sym_literal_int,
      sym_literal_str,
    ACTIONS(221), 3,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
  [1198] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 1,
      sym_ident,
    ACTIONS(227), 1,
      anon_sym_LBRACK_RBRACK,
    STATE(72), 2,
      sym__type,
      sym_slice_type,
  [1212] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(229), 1,
      sym_ident,
    ACTIONS(231), 1,
      anon_sym_end,
    STATE(58), 2,
      sym_record_component,
      aux_sym_record_components_repeat1,
  [1226] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 1,
      sym_ident,
    STATE(82), 1,
      sym_record_components,
    STATE(56), 2,
      sym_record_component,
      aux_sym_record_components_repeat1,
  [1240] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 1,
      sym_ident,
    ACTIONS(238), 1,
      anon_sym_end,
    STATE(58), 2,
      sym_record_component,
      aux_sym_record_components_repeat1,
  [1254] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 2,
      sym_ident,
      anon_sym_end,
  [1262] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(242), 1,
      anon_sym_do,
    ACTIONS(244), 1,
      anon_sym_end,
  [1272] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(246), 1,
      sym_ident,
    STATE(74), 1,
      sym_field_access,
  [1282] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 1,
      anon_sym_do,
    ACTIONS(250), 1,
      anon_sym_end,
  [1292] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 1,
      sym_ident,
  [1299] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 1,
      anon_sym_RBRACK,
  [1306] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      anon_sym_COMMA,
  [1313] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 1,
      sym_ident,
  [1320] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      anon_sym_SEMI,
  [1327] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      anon_sym_RBRACK,
  [1334] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(260), 1,
      anon_sym_RBRACK,
  [1341] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(262), 1,
      sym_ident,
  [1348] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(264), 1,
      anon_sym_in,
  [1355] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(266), 1,
      anon_sym_SEMI,
  [1362] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 1,
      anon_sym_DOT,
  [1369] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      anon_sym_RPAREN,
  [1376] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      anon_sym_foreach,
  [1383] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(272), 1,
      anon_sym_RPAREN,
  [1390] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(274), 1,
      anon_sym_RBRACK,
  [1397] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(276), 1,
      sym_ident,
  [1404] = 2,
    ACTIONS(278), 1,
      sym_comment,
    ACTIONS(280), 1,
      aux_sym_attr_token1,
  [1411] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(282), 1,
      sym_ident,
  [1418] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(284), 1,
      anon_sym_end,
  [1425] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(286), 1,
      anon_sym_end,
  [1432] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(288), 1,
      anon_sym_RPAREN,
  [1439] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(290), 1,
      anon_sym_SEMI,
  [1446] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(292), 1,
      anon_sym_EQ,
  [1453] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(294), 1,
      anon_sym_LPAREN,
  [1460] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(296), 1,
      sym_ident,
  [1467] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(298), 1,
      anon_sym_RPAREN,
  [1474] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(300), 1,
      ts_builtin_sym_end,
  [1481] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(302), 1,
      sym_ident,
  [1488] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 1,
      anon_sym_RBRACK,
  [1495] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(304), 1,
      sym_ident,
  [1502] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      anon_sym_RBRACK,
  [1509] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(306), 1,
      sym_ident,
  [1516] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(308), 1,
      anon_sym_RBRACK,
  [1523] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(310), 1,
      anon_sym_RBRACK,
  [1530] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(312), 1,
      sym_ident,
  [1537] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(314), 1,
      sym_ident,
  [1544] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(316), 1,
      sym_ident,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 35,
  [SMALL_STATE(4)] = 70,
  [SMALL_STATE(5)] = 106,
  [SMALL_STATE(6)] = 146,
  [SMALL_STATE(7)] = 186,
  [SMALL_STATE(8)] = 226,
  [SMALL_STATE(9)] = 262,
  [SMALL_STATE(10)] = 298,
  [SMALL_STATE(11)] = 334,
  [SMALL_STATE(12)] = 374,
  [SMALL_STATE(13)] = 404,
  [SMALL_STATE(14)] = 434,
  [SMALL_STATE(15)] = 464,
  [SMALL_STATE(16)] = 494,
  [SMALL_STATE(17)] = 521,
  [SMALL_STATE(18)] = 548,
  [SMALL_STATE(19)] = 575,
  [SMALL_STATE(20)] = 602,
  [SMALL_STATE(21)] = 629,
  [SMALL_STATE(22)] = 647,
  [SMALL_STATE(23)] = 665,
  [SMALL_STATE(24)] = 683,
  [SMALL_STATE(25)] = 707,
  [SMALL_STATE(26)] = 725,
  [SMALL_STATE(27)] = 743,
  [SMALL_STATE(28)] = 767,
  [SMALL_STATE(29)] = 785,
  [SMALL_STATE(30)] = 806,
  [SMALL_STATE(31)] = 823,
  [SMALL_STATE(32)] = 844,
  [SMALL_STATE(33)] = 865,
  [SMALL_STATE(34)] = 882,
  [SMALL_STATE(35)] = 898,
  [SMALL_STATE(36)] = 914,
  [SMALL_STATE(37)] = 930,
  [SMALL_STATE(38)] = 946,
  [SMALL_STATE(39)] = 962,
  [SMALL_STATE(40)] = 977,
  [SMALL_STATE(41)] = 994,
  [SMALL_STATE(42)] = 1008,
  [SMALL_STATE(43)] = 1022,
  [SMALL_STATE(44)] = 1036,
  [SMALL_STATE(45)] = 1050,
  [SMALL_STATE(46)] = 1064,
  [SMALL_STATE(47)] = 1078,
  [SMALL_STATE(48)] = 1092,
  [SMALL_STATE(49)] = 1106,
  [SMALL_STATE(50)] = 1120,
  [SMALL_STATE(51)] = 1134,
  [SMALL_STATE(52)] = 1151,
  [SMALL_STATE(53)] = 1168,
  [SMALL_STATE(54)] = 1185,
  [SMALL_STATE(55)] = 1198,
  [SMALL_STATE(56)] = 1212,
  [SMALL_STATE(57)] = 1226,
  [SMALL_STATE(58)] = 1240,
  [SMALL_STATE(59)] = 1254,
  [SMALL_STATE(60)] = 1262,
  [SMALL_STATE(61)] = 1272,
  [SMALL_STATE(62)] = 1282,
  [SMALL_STATE(63)] = 1292,
  [SMALL_STATE(64)] = 1299,
  [SMALL_STATE(65)] = 1306,
  [SMALL_STATE(66)] = 1313,
  [SMALL_STATE(67)] = 1320,
  [SMALL_STATE(68)] = 1327,
  [SMALL_STATE(69)] = 1334,
  [SMALL_STATE(70)] = 1341,
  [SMALL_STATE(71)] = 1348,
  [SMALL_STATE(72)] = 1355,
  [SMALL_STATE(73)] = 1362,
  [SMALL_STATE(74)] = 1369,
  [SMALL_STATE(75)] = 1376,
  [SMALL_STATE(76)] = 1383,
  [SMALL_STATE(77)] = 1390,
  [SMALL_STATE(78)] = 1397,
  [SMALL_STATE(79)] = 1404,
  [SMALL_STATE(80)] = 1411,
  [SMALL_STATE(81)] = 1418,
  [SMALL_STATE(82)] = 1425,
  [SMALL_STATE(83)] = 1432,
  [SMALL_STATE(84)] = 1439,
  [SMALL_STATE(85)] = 1446,
  [SMALL_STATE(86)] = 1453,
  [SMALL_STATE(87)] = 1460,
  [SMALL_STATE(88)] = 1467,
  [SMALL_STATE(89)] = 1474,
  [SMALL_STATE(90)] = 1481,
  [SMALL_STATE(91)] = 1488,
  [SMALL_STATE(92)] = 1495,
  [SMALL_STATE(93)] = 1502,
  [SMALL_STATE(94)] = 1509,
  [SMALL_STATE(95)] = 1516,
  [SMALL_STATE(96)] = 1523,
  [SMALL_STATE(97)] = 1530,
  [SMALL_STATE(98)] = 1537,
  [SMALL_STATE(99)] = 1544,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(97),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(94),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(92),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(90),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 2, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_templ_body_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_templ_body_repeat1, 2, 0, 0),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_templ_body_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [83] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_templ_body_repeat1, 2, 0, 0), SHIFT_REPEAT(98),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_templ_body_repeat1, 2, 0, 0), SHIFT_REPEAT(99),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_templ_body, 1, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_elements, 1, 0, 0),
  [101] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_templ_body_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [104] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_templ_body_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [107] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_templ_body_repeat1, 2, 0, 0), SHIFT_REPEAT(92),
  [110] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_templ_body_repeat1, 2, 0, 0), SHIFT_REPEAT(90),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 5, 0, 4),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 5, 0, 4),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 5, 0, 3),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 5, 0, 3),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 3, 0, 3),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 3, 0, 3),
  [125] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__operation_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__operation_repeat1, 2, 0, 0),
  [130] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__operation_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [133] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__operation_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 4, 0, 3),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 4, 0, 3),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 3, 0, 4),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 3, 0, 4),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__operation, 2, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 4, 0, 4),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 4, 0, 4),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_escape_char, 1, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_escape_char, 1, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attrs, 1, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attrs, 1, 0, 0),
  [162] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_attrs_repeat1, 2, 0, 0), SHIFT_REPEAT(85),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_attrs_repeat1, 2, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_attrs_repeat1, 2, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 3, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr, 3, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_namespace, 3, 0, 1),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_namespace, 3, 0, 1),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def_templ, 6, 0, 5),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_def_templ, 6, 0, 5),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def_record, 5, 0, 2),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_def_record, 5, 0, 2),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def_record, 3, 0, 2),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_def_record, 3, 0, 2),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def_templ, 4, 0, 5),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_def_templ, 4, 0, 5),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attr, 3, 0, 7),
  [195] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attr, 3, 0, 7),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__basic_expr, 1, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__basic_expr, 1, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [203] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field_access, 3, 0, 6),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_access, 3, 0, 6),
  [207] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal_bool, 1, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal_bool, 1, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_foreach_body_repeat1, 2, 0, 0),
  [213] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_foreach_body_repeat1, 2, 0, 0), SHIFT_REPEAT(92),
  [216] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_foreach_body_repeat1, 2, 0, 0), SHIFT_REPEAT(90),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_foreach_body, 1, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_operator, 1, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operator, 1, 0, 0),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [229] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [231] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_record_components, 1, 0, 0),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [235] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_record_components_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [238] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_record_components_repeat1, 2, 0, 0),
  [240] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_record_component, 3, 0, 8),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slice_type, 2, 0, 0),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_foreach, 10, 0, 9),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [278] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [280] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [300] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_tel(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_ident,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
