#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 107
#define LARGE_STATE_COUNT 6
#define SYMBOL_COUNT 63
#define ALIAS_COUNT 1
#define TOKEN_COUNT 32
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 13
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 21

enum ts_symbol_identifiers {
  sym_ident = 1,
  anon_sym_namespace = 2,
  anon_sym_SEMI = 3,
  sym_comment = 4,
  anon_sym_PLUS = 5,
  anon_sym_DASH = 6,
  anon_sym_STAR = 7,
  anon_sym_SLASH = 8,
  sym_int_lit = 9,
  anon_sym_DQUOTE = 10,
  aux_sym_str_lit_token1 = 11,
  anon_sym_BSLASH_LPAREN = 12,
  anon_sym_RPAREN = 13,
  anon_sym_SQUOTE = 14,
  aux_sym_str_lit_token2 = 15,
  sym_escape_char = 16,
  anon_sym_true = 17,
  anon_sym_false = 18,
  anon_sym_COLON = 19,
  anon_sym_BSLASH = 20,
  anon_sym_LBRACK = 21,
  anon_sym_LPAREN = 22,
  anon_sym_LBRACK_RBRACK = 23,
  anon_sym_DOT = 24,
  anon_sym_RBRACK = 25,
  anon_sym_EQ = 26,
  aux_sym_attr_token1 = 27,
  anon_sym_record = 28,
  anon_sym_end = 29,
  anon_sym_do = 30,
  anon_sym_templ = 31,
  sym_source = 32,
  sym_namespace = 33,
  sym_sym = 34,
  sym_str_lit = 35,
  sym_bool_lit = 36,
  sym_kwd_lit = 37,
  sym_escape = 38,
  sym__def = 39,
  sym__form = 40,
  sym__type = 41,
  sym_attrs = 42,
  sym_slice_lit = 43,
  sym_field_access = 44,
  sym_fields = 45,
  sym_field = 46,
  sym__expr = 47,
  sym_list_lit = 48,
  sym_element = 49,
  aux_sym__elements = 50,
  sym_attr = 51,
  sym_def_record = 52,
  sym__record_body = 53,
  sym_def_templ = 54,
  sym__templ_body = 55,
  aux_sym_source_repeat1 = 56,
  aux_sym_str_lit_repeat1 = 57,
  aux_sym_str_lit_repeat2 = 58,
  aux_sym_attrs_repeat1 = 59,
  aux_sym_fields_repeat1 = 60,
  aux_sym_list_lit_repeat1 = 61,
  aux_sym__templ_body_repeat1 = 62,
  alias_sym_children = 63,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_ident] = "ident",
  [anon_sym_namespace] = "namespace",
  [anon_sym_SEMI] = ";",
  [sym_comment] = "comment",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [sym_int_lit] = "int_lit",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_str_lit_token1] = "str_lit_token1",
  [anon_sym_BSLASH_LPAREN] = "\\(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_str_lit_token2] = "str_lit_token2",
  [sym_escape_char] = "escape_char",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_COLON] = ":",
  [anon_sym_BSLASH] = "\\",
  [anon_sym_LBRACK] = "[",
  [anon_sym_LPAREN] = "(",
  [anon_sym_LBRACK_RBRACK] = "[]",
  [anon_sym_DOT] = ".",
  [anon_sym_RBRACK] = "]",
  [anon_sym_EQ] = "=",
  [aux_sym_attr_token1] = "text",
  [anon_sym_record] = "record",
  [anon_sym_end] = "end",
  [anon_sym_do] = "do",
  [anon_sym_templ] = "templ",
  [sym_source] = "source",
  [sym_namespace] = "namespace",
  [sym_sym] = "sym",
  [sym_str_lit] = "str_lit",
  [sym_bool_lit] = "bool_lit",
  [sym_kwd_lit] = "kwd_lit",
  [sym_escape] = "escape",
  [sym__def] = "_def",
  [sym__form] = "_form",
  [sym__type] = "_type",
  [sym_attrs] = "attrs",
  [sym_slice_lit] = "slice_lit",
  [sym_field_access] = "field_access",
  [sym_fields] = "fields",
  [sym_field] = "field",
  [sym__expr] = "_expr",
  [sym_list_lit] = "list_lit",
  [sym_element] = "element",
  [aux_sym__elements] = "_elements",
  [sym_attr] = "attr",
  [sym_def_record] = "def_record",
  [sym__record_body] = "_record_body",
  [sym_def_templ] = "def_templ",
  [sym__templ_body] = "body",
  [aux_sym_source_repeat1] = "source_repeat1",
  [aux_sym_str_lit_repeat1] = "str_lit_repeat1",
  [aux_sym_str_lit_repeat2] = "str_lit_repeat2",
  [aux_sym_attrs_repeat1] = "attrs_repeat1",
  [aux_sym_fields_repeat1] = "fields_repeat1",
  [aux_sym_list_lit_repeat1] = "list_lit_repeat1",
  [aux_sym__templ_body_repeat1] = "_templ_body_repeat1",
  [alias_sym_children] = "children",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_ident] = sym_ident,
  [anon_sym_namespace] = anon_sym_namespace,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym_comment] = sym_comment,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [sym_int_lit] = sym_int_lit,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_str_lit_token1] = aux_sym_str_lit_token1,
  [anon_sym_BSLASH_LPAREN] = anon_sym_BSLASH_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_str_lit_token2] = aux_sym_str_lit_token2,
  [sym_escape_char] = sym_escape_char,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_LBRACK_RBRACK] = anon_sym_LBRACK_RBRACK,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_EQ] = anon_sym_EQ,
  [aux_sym_attr_token1] = aux_sym_attr_token1,
  [anon_sym_record] = anon_sym_record,
  [anon_sym_end] = anon_sym_end,
  [anon_sym_do] = anon_sym_do,
  [anon_sym_templ] = anon_sym_templ,
  [sym_source] = sym_source,
  [sym_namespace] = sym_namespace,
  [sym_sym] = sym_sym,
  [sym_str_lit] = sym_str_lit,
  [sym_bool_lit] = sym_bool_lit,
  [sym_kwd_lit] = sym_kwd_lit,
  [sym_escape] = sym_escape,
  [sym__def] = sym__def,
  [sym__form] = sym__form,
  [sym__type] = sym__type,
  [sym_attrs] = sym_attrs,
  [sym_slice_lit] = sym_slice_lit,
  [sym_field_access] = sym_field_access,
  [sym_fields] = sym_fields,
  [sym_field] = sym_field,
  [sym__expr] = sym__expr,
  [sym_list_lit] = sym_list_lit,
  [sym_element] = sym_element,
  [aux_sym__elements] = aux_sym__elements,
  [sym_attr] = sym_attr,
  [sym_def_record] = sym_def_record,
  [sym__record_body] = sym__record_body,
  [sym_def_templ] = sym_def_templ,
  [sym__templ_body] = sym__templ_body,
  [aux_sym_source_repeat1] = aux_sym_source_repeat1,
  [aux_sym_str_lit_repeat1] = aux_sym_str_lit_repeat1,
  [aux_sym_str_lit_repeat2] = aux_sym_str_lit_repeat2,
  [aux_sym_attrs_repeat1] = aux_sym_attrs_repeat1,
  [aux_sym_fields_repeat1] = aux_sym_fields_repeat1,
  [aux_sym_list_lit_repeat1] = aux_sym_list_lit_repeat1,
  [aux_sym__templ_body_repeat1] = aux_sym__templ_body_repeat1,
  [alias_sym_children] = alias_sym_children,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_namespace] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_int_lit] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_str_lit_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BSLASH_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_str_lit_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_escape_char] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_attr_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_record] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_end] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_do] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_templ] = {
    .visible = true,
    .named = false,
  },
  [sym_source] = {
    .visible = true,
    .named = true,
  },
  [sym_namespace] = {
    .visible = true,
    .named = true,
  },
  [sym_sym] = {
    .visible = true,
    .named = true,
  },
  [sym_str_lit] = {
    .visible = true,
    .named = true,
  },
  [sym_bool_lit] = {
    .visible = true,
    .named = true,
  },
  [sym_kwd_lit] = {
    .visible = true,
    .named = true,
  },
  [sym_escape] = {
    .visible = true,
    .named = true,
  },
  [sym__def] = {
    .visible = false,
    .named = true,
  },
  [sym__form] = {
    .visible = false,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym_attrs] = {
    .visible = true,
    .named = true,
  },
  [sym_slice_lit] = {
    .visible = true,
    .named = true,
  },
  [sym_field_access] = {
    .visible = true,
    .named = true,
  },
  [sym_fields] = {
    .visible = true,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym__expr] = {
    .visible = false,
    .named = true,
  },
  [sym_list_lit] = {
    .visible = true,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__elements] = {
    .visible = false,
    .named = false,
  },
  [sym_attr] = {
    .visible = true,
    .named = true,
  },
  [sym_def_record] = {
    .visible = true,
    .named = true,
  },
  [sym__record_body] = {
    .visible = false,
    .named = true,
  },
  [sym_def_templ] = {
    .visible = true,
    .named = true,
  },
  [sym__templ_body] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_str_lit_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_str_lit_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_attrs_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_fields_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_lit_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__templ_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_children] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_close = 2,
  field_field = 3,
  field_key = 4,
  field_marker = 5,
  field_name = 6,
  field_object = 7,
  field_open = 8,
  field_tag = 9,
  field_templ = 10,
  field_type = 11,
  field_value = 12,
  field_var = 13,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_close] = "close",
  [field_field] = "field",
  [field_key] = "key",
  [field_marker] = "marker",
  [field_name] = "name",
  [field_object] = "object",
  [field_open] = "open",
  [field_tag] = "tag",
  [field_templ] = "templ",
  [field_type] = "type",
  [field_value] = "value",
  [field_var] = "var",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 3},
  [6] = {.index = 9, .length = 6},
  [7] = {.index = 15, .length = 3},
  [8] = {.index = 18, .length = 3},
  [9] = {.index = 21, .length = 2},
  [10] = {.index = 23, .length = 3},
  [11] = {.index = 26, .length = 3},
  [12] = {.index = 29, .length = 3},
  [13] = {.index = 29, .length = 3},
  [14] = {.index = 32, .length = 1},
  [15] = {.index = 33, .length = 5},
  [16] = {.index = 38, .length = 4},
  [17] = {.index = 42, .length = 2},
  [18] = {.index = 44, .length = 3},
  [19] = {.index = 47, .length = 5},
  [20] = {.index = 52, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_marker, 0},
    {field_name, 1},
  [2] =
    {field_value, 0},
  [3] =
    {field_name, 1},
  [4] =
    {field_field, 2},
    {field_object, 0},
  [6] =
    {field_close, 1, .inherited = true},
    {field_open, 1, .inherited = true},
    {field_templ, 1, .inherited = true},
  [9] =
    {field_close, 0, .inherited = true},
    {field_close, 1, .inherited = true},
    {field_open, 0, .inherited = true},
    {field_open, 1, .inherited = true},
    {field_templ, 0, .inherited = true},
    {field_templ, 1, .inherited = true},
  [15] =
    {field_close, 2},
    {field_open, 0},
    {field_tag, 1},
  [18] =
    {field_close, 2},
    {field_open, 0},
    {field_value, 1, .inherited = true},
  [21] =
    {field_value, 0, .inherited = true},
    {field_value, 1, .inherited = true},
  [23] =
    {field_close, 2},
    {field_name, 1},
    {field_open, 0},
  [26] =
    {field_close, 2},
    {field_open, 0},
    {field_templ, 1},
  [29] =
    {field_close, 3},
    {field_open, 0},
    {field_tag, 1},
  [32] =
    {field_marker, 0},
  [33] =
    {field_body, 2},
    {field_close, 3},
    {field_marker, 2, .inherited = true},
    {field_name, 1},
    {field_open, 0},
  [38] =
    {field_close, 3},
    {field_open, 0},
    {field_type, 2},
    {field_var, 1},
  [42] =
    {field_key, 0},
    {field_value, 2},
  [44] =
    {field_close, 4},
    {field_open, 0},
    {field_tag, 1},
  [47] =
    {field_close, 4},
    {field_marker, 3, .inherited = true},
    {field_open, 0},
    {field_type, 2},
    {field_var, 1},
  [52] =
    {field_name, 0},
    {field_type, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [13] = {
    [2] = alias_sym_children,
  },
  [18] = {
    [3] = alias_sym_children,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  aux_sym__elements, 2,
    aux_sym__elements,
    alias_sym_children,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 6,
  [8] = 8,
  [9] = 9,
  [10] = 8,
  [11] = 11,
  [12] = 12,
  [13] = 12,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 9,
  [18] = 18,
  [19] = 11,
  [20] = 20,
  [21] = 21,
  [22] = 20,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 25,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 30,
  [42] = 42,
  [43] = 31,
  [44] = 27,
  [45] = 45,
  [46] = 42,
  [47] = 34,
  [48] = 48,
  [49] = 49,
  [50] = 35,
  [51] = 28,
  [52] = 26,
  [53] = 33,
  [54] = 32,
  [55] = 55,
  [56] = 39,
  [57] = 37,
  [58] = 38,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 65,
  [70] = 70,
  [71] = 67,
  [72] = 66,
  [73] = 70,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 80,
  [84] = 84,
  [85] = 85,
  [86] = 85,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 95,
  [104] = 104,
  [105] = 97,
  [106] = 106,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      ADVANCE_MAP(
        '"', 23,
        '#', 14,
        '\'', 28,
        '(', 35,
        ')', 27,
        '*', 19,
        '+', 17,
        '-', 18,
        '.', 37,
        '/', 20,
        '0', 21,
        ':', 32,
        ';', 8,
        '=', 39,
        '[', 34,
        '\\', 33,
        ']', 38,
        '_', 10,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(22);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(13);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(23);
      if (lookahead == '#') ADVANCE(14);
      if (lookahead == '\\') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(14);
      if (lookahead == '\'') ADVANCE(28);
      if (lookahead == '\\') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0) ADVANCE(29);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(14);
      if (lookahead == '[') ADVANCE(5);
      if (lookahead == '_') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(13);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 4:
      if (lookahead == '(') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '[' &&
          lookahead != '{') ADVANCE(31);
      END_STATE();
    case 5:
      if (lookahead == ']') ADVANCE(36);
      END_STATE();
    case 6:
      if (eof) ADVANCE(7);
      ADVANCE_MAP(
        '"', 23,
        '#', 14,
        '\'', 28,
        '(', 35,
        ')', 27,
        '*', 19,
        '+', 17,
        '-', 18,
        '.', 37,
        '/', 20,
        '0', 21,
        ':', 32,
        ';', 8,
        '[', 34,
        '\\', 33,
        ']', 38,
        '_', 10,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(22);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(13);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '-') ADVANCE(11);
      if (lookahead == '_') ADVANCE(12);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(13);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '_') ADVANCE(12);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(13);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '-' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_ident);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '#') ADVANCE(14);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '#') ADVANCE(15);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == ']') ADVANCE(14);
      if (lookahead != 0) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '#') ADVANCE(14);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_int_lit);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_int_lit);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_str_lit_token1);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_str_lit_token1);
      if (lookahead == '#') ADVANCE(14);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '\\') ADVANCE(24);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_BSLASH_LPAREN);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_str_lit_token2);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_str_lit_token2);
      if (lookahead == '#') ADVANCE(14);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(29);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_escape_char);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_LBRACK_RBRACK);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_attr_token1);
      if (lookahead == '#') ADVANCE(15);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ']') ADVANCE(41);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_attr_token1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ']') ADVANCE(41);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'd') ADVANCE(1);
      if (lookahead == 'e') ADVANCE(2);
      if (lookahead == 'f') ADVANCE(3);
      if (lookahead == 'n') ADVANCE(4);
      if (lookahead == 'r') ADVANCE(5);
      if (lookahead == 't') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'o') ADVANCE(7);
      END_STATE();
    case 2:
      if (lookahead == 'n') ADVANCE(8);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(9);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(10);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(11);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(12);
      if (lookahead == 'r') ADVANCE(13);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_do);
      END_STATE();
    case 8:
      if (lookahead == 'd') ADVANCE(14);
      END_STATE();
    case 9:
      if (lookahead == 'l') ADVANCE(15);
      END_STATE();
    case 10:
      if (lookahead == 'm') ADVANCE(16);
      END_STATE();
    case 11:
      if (lookahead == 'c') ADVANCE(17);
      END_STATE();
    case 12:
      if (lookahead == 'm') ADVANCE(18);
      END_STATE();
    case 13:
      if (lookahead == 'u') ADVANCE(19);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_end);
      END_STATE();
    case 15:
      if (lookahead == 's') ADVANCE(20);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 17:
      if (lookahead == 'o') ADVANCE(22);
      END_STATE();
    case 18:
      if (lookahead == 'p') ADVANCE(23);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(25);
      END_STATE();
    case 21:
      if (lookahead == 's') ADVANCE(26);
      END_STATE();
    case 22:
      if (lookahead == 'r') ADVANCE(27);
      END_STATE();
    case 23:
      if (lookahead == 'l') ADVANCE(28);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 26:
      if (lookahead == 'p') ADVANCE(29);
      END_STATE();
    case 27:
      if (lookahead == 'd') ADVANCE(30);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_templ);
      END_STATE();
    case 29:
      if (lookahead == 'a') ADVANCE(31);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_record);
      END_STATE();
    case 31:
      if (lookahead == 'c') ADVANCE(32);
      END_STATE();
    case 32:
      if (lookahead == 'e') ADVANCE(33);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_namespace);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 1},
  [65] = {.lex_state = 2},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 2},
  [68] = {.lex_state = 2},
  [69] = {.lex_state = 2},
  [70] = {.lex_state = 1},
  [71] = {.lex_state = 2},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 2},
  [77] = {.lex_state = 1},
  [78] = {.lex_state = 3},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 40},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_ident] = ACTIONS(1),
    [anon_sym_namespace] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [sym_int_lit] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_record] = ACTIONS(1),
    [anon_sym_end] = ACTIONS(1),
    [anon_sym_do] = ACTIONS(1),
    [anon_sym_templ] = ACTIONS(1),
  },
  [1] = {
    [sym_source] = STATE(94),
    [sym_namespace] = STATE(2),
    [sym_sym] = STATE(5),
    [sym_str_lit] = STATE(5),
    [sym_bool_lit] = STATE(5),
    [sym_kwd_lit] = STATE(5),
    [sym_escape] = STATE(5),
    [sym__def] = STATE(5),
    [sym__form] = STATE(5),
    [sym_field_access] = STATE(5),
    [sym__expr] = STATE(5),
    [sym_list_lit] = STATE(5),
    [sym_element] = STATE(5),
    [sym_def_record] = STATE(5),
    [sym_def_templ] = STATE(5),
    [aux_sym_source_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_ident] = ACTIONS(7),
    [anon_sym_namespace] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
    [anon_sym_PLUS] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_STAR] = ACTIONS(11),
    [anon_sym_SLASH] = ACTIONS(11),
    [sym_int_lit] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [anon_sym_SQUOTE] = ACTIONS(17),
    [anon_sym_true] = ACTIONS(19),
    [anon_sym_false] = ACTIONS(19),
    [anon_sym_COLON] = ACTIONS(21),
    [anon_sym_BSLASH] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(27),
    [anon_sym_record] = ACTIONS(29),
    [anon_sym_templ] = ACTIONS(31),
  },
  [2] = {
    [sym_sym] = STATE(4),
    [sym_str_lit] = STATE(4),
    [sym_bool_lit] = STATE(4),
    [sym_kwd_lit] = STATE(4),
    [sym_escape] = STATE(4),
    [sym__def] = STATE(4),
    [sym__form] = STATE(4),
    [sym_field_access] = STATE(4),
    [sym__expr] = STATE(4),
    [sym_list_lit] = STATE(4),
    [sym_element] = STATE(4),
    [sym_def_record] = STATE(4),
    [sym_def_templ] = STATE(4),
    [aux_sym_source_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(33),
    [sym_ident] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
    [anon_sym_PLUS] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_STAR] = ACTIONS(11),
    [anon_sym_SLASH] = ACTIONS(11),
    [sym_int_lit] = ACTIONS(35),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [anon_sym_SQUOTE] = ACTIONS(17),
    [anon_sym_true] = ACTIONS(19),
    [anon_sym_false] = ACTIONS(19),
    [anon_sym_COLON] = ACTIONS(21),
    [anon_sym_BSLASH] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(27),
    [anon_sym_record] = ACTIONS(29),
    [anon_sym_templ] = ACTIONS(31),
  },
  [3] = {
    [sym_sym] = STATE(3),
    [sym_str_lit] = STATE(3),
    [sym_bool_lit] = STATE(3),
    [sym_kwd_lit] = STATE(3),
    [sym_escape] = STATE(3),
    [sym__def] = STATE(3),
    [sym__form] = STATE(3),
    [sym_field_access] = STATE(3),
    [sym__expr] = STATE(3),
    [sym_list_lit] = STATE(3),
    [sym_element] = STATE(3),
    [sym_def_record] = STATE(3),
    [sym_def_templ] = STATE(3),
    [aux_sym_source_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(37),
    [sym_ident] = ACTIONS(39),
    [sym_comment] = ACTIONS(3),
    [anon_sym_PLUS] = ACTIONS(42),
    [anon_sym_DASH] = ACTIONS(42),
    [anon_sym_STAR] = ACTIONS(42),
    [anon_sym_SLASH] = ACTIONS(42),
    [sym_int_lit] = ACTIONS(45),
    [anon_sym_DQUOTE] = ACTIONS(48),
    [anon_sym_SQUOTE] = ACTIONS(51),
    [anon_sym_true] = ACTIONS(54),
    [anon_sym_false] = ACTIONS(54),
    [anon_sym_COLON] = ACTIONS(57),
    [anon_sym_BSLASH] = ACTIONS(60),
    [anon_sym_LBRACK] = ACTIONS(63),
    [anon_sym_LPAREN] = ACTIONS(66),
    [anon_sym_record] = ACTIONS(69),
    [anon_sym_templ] = ACTIONS(72),
  },
  [4] = {
    [sym_sym] = STATE(3),
    [sym_str_lit] = STATE(3),
    [sym_bool_lit] = STATE(3),
    [sym_kwd_lit] = STATE(3),
    [sym_escape] = STATE(3),
    [sym__def] = STATE(3),
    [sym__form] = STATE(3),
    [sym_field_access] = STATE(3),
    [sym__expr] = STATE(3),
    [sym_list_lit] = STATE(3),
    [sym_element] = STATE(3),
    [sym_def_record] = STATE(3),
    [sym_def_templ] = STATE(3),
    [aux_sym_source_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(75),
    [sym_ident] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
    [anon_sym_PLUS] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_STAR] = ACTIONS(11),
    [anon_sym_SLASH] = ACTIONS(11),
    [sym_int_lit] = ACTIONS(77),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [anon_sym_SQUOTE] = ACTIONS(17),
    [anon_sym_true] = ACTIONS(19),
    [anon_sym_false] = ACTIONS(19),
    [anon_sym_COLON] = ACTIONS(21),
    [anon_sym_BSLASH] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(27),
    [anon_sym_record] = ACTIONS(29),
    [anon_sym_templ] = ACTIONS(31),
  },
  [5] = {
    [sym_sym] = STATE(3),
    [sym_str_lit] = STATE(3),
    [sym_bool_lit] = STATE(3),
    [sym_kwd_lit] = STATE(3),
    [sym_escape] = STATE(3),
    [sym__def] = STATE(3),
    [sym__form] = STATE(3),
    [sym_field_access] = STATE(3),
    [sym__expr] = STATE(3),
    [sym_list_lit] = STATE(3),
    [sym_element] = STATE(3),
    [sym_def_record] = STATE(3),
    [sym_def_templ] = STATE(3),
    [aux_sym_source_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(33),
    [sym_ident] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
    [anon_sym_PLUS] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_STAR] = ACTIONS(11),
    [anon_sym_SLASH] = ACTIONS(11),
    [sym_int_lit] = ACTIONS(77),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [anon_sym_SQUOTE] = ACTIONS(17),
    [anon_sym_true] = ACTIONS(19),
    [anon_sym_false] = ACTIONS(19),
    [anon_sym_COLON] = ACTIONS(21),
    [anon_sym_BSLASH] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(27),
    [anon_sym_record] = ACTIONS(29),
    [anon_sym_templ] = ACTIONS(31),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      sym_ident,
    ACTIONS(83), 1,
      sym_int_lit,
    ACTIONS(85), 1,
      anon_sym_DQUOTE,
    ACTIONS(87), 1,
      anon_sym_SQUOTE,
    ACTIONS(91), 1,
      anon_sym_COLON,
    ACTIONS(93), 1,
      anon_sym_BSLASH,
    ACTIONS(95), 1,
      anon_sym_LBRACK,
    ACTIONS(97), 1,
      anon_sym_LPAREN,
    ACTIONS(99), 1,
      anon_sym_RBRACK,
    STATE(10), 1,
      sym_attrs,
    STATE(11), 1,
      aux_sym__elements,
    ACTIONS(89), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(48), 2,
      sym_attr,
      aux_sym_attrs_repeat1,
    ACTIONS(81), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(63), 10,
      sym_sym,
      sym_str_lit,
      sym_bool_lit,
      sym_kwd_lit,
      sym_escape,
      sym__form,
      sym_field_access,
      sym__expr,
      sym_list_lit,
      sym_element,
  [63] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      sym_ident,
    ACTIONS(83), 1,
      sym_int_lit,
    ACTIONS(85), 1,
      anon_sym_DQUOTE,
    ACTIONS(87), 1,
      anon_sym_SQUOTE,
    ACTIONS(91), 1,
      anon_sym_COLON,
    ACTIONS(93), 1,
      anon_sym_BSLASH,
    ACTIONS(95), 1,
      anon_sym_LBRACK,
    ACTIONS(97), 1,
      anon_sym_LPAREN,
    ACTIONS(101), 1,
      anon_sym_RBRACK,
    STATE(8), 1,
      sym_attrs,
    STATE(19), 1,
      aux_sym__elements,
    ACTIONS(89), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(48), 2,
      sym_attr,
      aux_sym_attrs_repeat1,
    ACTIONS(81), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(63), 10,
      sym_sym,
      sym_str_lit,
      sym_bool_lit,
      sym_kwd_lit,
      sym_escape,
      sym__form,
      sym_field_access,
      sym__expr,
      sym_list_lit,
      sym_element,
  [126] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 1,
      sym_int_lit,
    ACTIONS(85), 1,
      anon_sym_DQUOTE,
    ACTIONS(87), 1,
      anon_sym_SQUOTE,
    ACTIONS(91), 1,
      anon_sym_COLON,
    ACTIONS(93), 1,
      anon_sym_BSLASH,
    ACTIONS(95), 1,
      anon_sym_LBRACK,
    ACTIONS(97), 1,
      anon_sym_LPAREN,
    ACTIONS(103), 1,
      sym_ident,
    ACTIONS(105), 1,
      anon_sym_RBRACK,
    STATE(17), 1,
      aux_sym__elements,
    ACTIONS(89), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(81), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(63), 10,
      sym_sym,
      sym_str_lit,
      sym_bool_lit,
      sym_kwd_lit,
      sym_escape,
      sym__form,
      sym_field_access,
      sym__expr,
      sym_list_lit,
      sym_element,
  [182] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 1,
      sym_int_lit,
    ACTIONS(85), 1,
      anon_sym_DQUOTE,
    ACTIONS(87), 1,
      anon_sym_SQUOTE,
    ACTIONS(91), 1,
      anon_sym_COLON,
    ACTIONS(93), 1,
      anon_sym_BSLASH,
    ACTIONS(95), 1,
      anon_sym_LBRACK,
    ACTIONS(97), 1,
      anon_sym_LPAREN,
    ACTIONS(103), 1,
      sym_ident,
    ACTIONS(107), 1,
      anon_sym_RBRACK,
    STATE(18), 1,
      aux_sym__elements,
    ACTIONS(89), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(81), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(63), 10,
      sym_sym,
      sym_str_lit,
      sym_bool_lit,
      sym_kwd_lit,
      sym_escape,
      sym__form,
      sym_field_access,
      sym__expr,
      sym_list_lit,
      sym_element,
  [238] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 1,
      sym_int_lit,
    ACTIONS(85), 1,
      anon_sym_DQUOTE,
    ACTIONS(87), 1,
      anon_sym_SQUOTE,
    ACTIONS(91), 1,
      anon_sym_COLON,
    ACTIONS(93), 1,
      anon_sym_BSLASH,
    ACTIONS(95), 1,
      anon_sym_LBRACK,
    ACTIONS(97), 1,
      anon_sym_LPAREN,
    ACTIONS(103), 1,
      sym_ident,
    ACTIONS(109), 1,
      anon_sym_RBRACK,
    STATE(9), 1,
      aux_sym__elements,
    ACTIONS(89), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(81), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(63), 10,
      sym_sym,
      sym_str_lit,
      sym_bool_lit,
      sym_kwd_lit,
      sym_escape,
      sym__form,
      sym_field_access,
      sym__expr,
      sym_list_lit,
      sym_element,
  [294] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 1,
      sym_int_lit,
    ACTIONS(85), 1,
      anon_sym_DQUOTE,
    ACTIONS(87), 1,
      anon_sym_SQUOTE,
    ACTIONS(91), 1,
      anon_sym_COLON,
    ACTIONS(93), 1,
      anon_sym_BSLASH,
    ACTIONS(95), 1,
      anon_sym_LBRACK,
    ACTIONS(97), 1,
      anon_sym_LPAREN,
    ACTIONS(103), 1,
      sym_ident,
    ACTIONS(111), 1,
      anon_sym_RBRACK,
    STATE(18), 1,
      aux_sym__elements,
    ACTIONS(89), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(81), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(63), 10,
      sym_sym,
      sym_str_lit,
      sym_bool_lit,
      sym_kwd_lit,
      sym_escape,
      sym__form,
      sym_field_access,
      sym__expr,
      sym_list_lit,
      sym_element,
  [350] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_DQUOTE,
    ACTIONS(87), 1,
      anon_sym_SQUOTE,
    ACTIONS(91), 1,
      anon_sym_COLON,
    ACTIONS(93), 1,
      anon_sym_BSLASH,
    ACTIONS(95), 1,
      anon_sym_LBRACK,
    ACTIONS(97), 1,
      anon_sym_LPAREN,
    ACTIONS(103), 1,
      sym_ident,
    ACTIONS(113), 1,
      sym_int_lit,
    ACTIONS(115), 1,
      anon_sym_RPAREN,
    STATE(14), 1,
      aux_sym_list_lit_repeat1,
    ACTIONS(89), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(81), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(62), 10,
      sym_sym,
      sym_str_lit,
      sym_bool_lit,
      sym_kwd_lit,
      sym_escape,
      sym__form,
      sym_field_access,
      sym__expr,
      sym_list_lit,
      sym_element,
  [406] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_DQUOTE,
    ACTIONS(87), 1,
      anon_sym_SQUOTE,
    ACTIONS(91), 1,
      anon_sym_COLON,
    ACTIONS(93), 1,
      anon_sym_BSLASH,
    ACTIONS(95), 1,
      anon_sym_LBRACK,
    ACTIONS(97), 1,
      anon_sym_LPAREN,
    ACTIONS(103), 1,
      sym_ident,
    ACTIONS(113), 1,
      sym_int_lit,
    ACTIONS(117), 1,
      anon_sym_RPAREN,
    STATE(14), 1,
      aux_sym_list_lit_repeat1,
    ACTIONS(89), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(81), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(62), 10,
      sym_sym,
      sym_str_lit,
      sym_bool_lit,
      sym_kwd_lit,
      sym_escape,
      sym__form,
      sym_field_access,
      sym__expr,
      sym_list_lit,
      sym_element,
  [462] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 1,
      sym_ident,
    ACTIONS(125), 1,
      sym_int_lit,
    ACTIONS(128), 1,
      anon_sym_DQUOTE,
    ACTIONS(131), 1,
      anon_sym_RPAREN,
    ACTIONS(133), 1,
      anon_sym_SQUOTE,
    ACTIONS(139), 1,
      anon_sym_COLON,
    ACTIONS(142), 1,
      anon_sym_BSLASH,
    ACTIONS(145), 1,
      anon_sym_LBRACK,
    ACTIONS(148), 1,
      anon_sym_LPAREN,
    STATE(14), 1,
      aux_sym_list_lit_repeat1,
    ACTIONS(136), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(122), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(62), 10,
      sym_sym,
      sym_str_lit,
      sym_bool_lit,
      sym_kwd_lit,
      sym_escape,
      sym__form,
      sym_field_access,
      sym__expr,
      sym_list_lit,
      sym_element,
  [518] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 1,
      sym_ident,
    ACTIONS(157), 1,
      sym_int_lit,
    ACTIONS(160), 1,
      anon_sym_DQUOTE,
    ACTIONS(163), 1,
      anon_sym_SQUOTE,
    ACTIONS(169), 1,
      anon_sym_COLON,
    ACTIONS(172), 1,
      anon_sym_BSLASH,
    ACTIONS(175), 1,
      anon_sym_LBRACK,
    ACTIONS(178), 1,
      anon_sym_LPAREN,
    ACTIONS(181), 1,
      anon_sym_end,
    ACTIONS(166), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(154), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(15), 11,
      sym_sym,
      sym_str_lit,
      sym_bool_lit,
      sym_kwd_lit,
      sym_escape,
      sym__form,
      sym_field_access,
      sym__expr,
      sym_list_lit,
      sym_element,
      aux_sym__templ_body_repeat1,
  [572] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_DQUOTE,
    ACTIONS(87), 1,
      anon_sym_SQUOTE,
    ACTIONS(91), 1,
      anon_sym_COLON,
    ACTIONS(93), 1,
      anon_sym_BSLASH,
    ACTIONS(95), 1,
      anon_sym_LBRACK,
    ACTIONS(97), 1,
      anon_sym_LPAREN,
    ACTIONS(103), 1,
      sym_ident,
    ACTIONS(183), 1,
      sym_int_lit,
    ACTIONS(185), 1,
      anon_sym_end,
    ACTIONS(89), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(81), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(15), 11,
      sym_sym,
      sym_str_lit,
      sym_bool_lit,
      sym_kwd_lit,
      sym_escape,
      sym__form,
      sym_field_access,
      sym__expr,
      sym_list_lit,
      sym_element,
      aux_sym__templ_body_repeat1,
  [626] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 1,
      sym_int_lit,
    ACTIONS(85), 1,
      anon_sym_DQUOTE,
    ACTIONS(87), 1,
      anon_sym_SQUOTE,
    ACTIONS(91), 1,
      anon_sym_COLON,
    ACTIONS(93), 1,
      anon_sym_BSLASH,
    ACTIONS(95), 1,
      anon_sym_LBRACK,
    ACTIONS(97), 1,
      anon_sym_LPAREN,
    ACTIONS(103), 1,
      sym_ident,
    ACTIONS(187), 1,
      anon_sym_RBRACK,
    STATE(18), 1,
      aux_sym__elements,
    ACTIONS(89), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(81), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(63), 10,
      sym_sym,
      sym_str_lit,
      sym_bool_lit,
      sym_kwd_lit,
      sym_escape,
      sym__form,
      sym_field_access,
      sym__expr,
      sym_list_lit,
      sym_element,
  [682] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 1,
      sym_ident,
    ACTIONS(195), 1,
      sym_int_lit,
    ACTIONS(198), 1,
      anon_sym_DQUOTE,
    ACTIONS(201), 1,
      anon_sym_SQUOTE,
    ACTIONS(207), 1,
      anon_sym_COLON,
    ACTIONS(210), 1,
      anon_sym_BSLASH,
    ACTIONS(213), 1,
      anon_sym_LBRACK,
    ACTIONS(216), 1,
      anon_sym_LPAREN,
    ACTIONS(219), 1,
      anon_sym_RBRACK,
    STATE(18), 1,
      aux_sym__elements,
    ACTIONS(204), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(192), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(63), 10,
      sym_sym,
      sym_str_lit,
      sym_bool_lit,
      sym_kwd_lit,
      sym_escape,
      sym__form,
      sym_field_access,
      sym__expr,
      sym_list_lit,
      sym_element,
  [738] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 1,
      sym_int_lit,
    ACTIONS(85), 1,
      anon_sym_DQUOTE,
    ACTIONS(87), 1,
      anon_sym_SQUOTE,
    ACTIONS(91), 1,
      anon_sym_COLON,
    ACTIONS(93), 1,
      anon_sym_BSLASH,
    ACTIONS(95), 1,
      anon_sym_LBRACK,
    ACTIONS(97), 1,
      anon_sym_LPAREN,
    ACTIONS(103), 1,
      sym_ident,
    ACTIONS(221), 1,
      anon_sym_RBRACK,
    STATE(18), 1,
      aux_sym__elements,
    ACTIONS(89), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(81), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(63), 10,
      sym_sym,
      sym_str_lit,
      sym_bool_lit,
      sym_kwd_lit,
      sym_escape,
      sym__form,
      sym_field_access,
      sym__expr,
      sym_list_lit,
      sym_element,
  [794] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_DQUOTE,
    ACTIONS(87), 1,
      anon_sym_SQUOTE,
    ACTIONS(91), 1,
      anon_sym_COLON,
    ACTIONS(93), 1,
      anon_sym_BSLASH,
    ACTIONS(95), 1,
      anon_sym_LBRACK,
    ACTIONS(97), 1,
      anon_sym_LPAREN,
    ACTIONS(103), 1,
      sym_ident,
    ACTIONS(113), 1,
      sym_int_lit,
    STATE(12), 1,
      aux_sym_list_lit_repeat1,
    ACTIONS(89), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(81), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(62), 10,
      sym_sym,
      sym_str_lit,
      sym_bool_lit,
      sym_kwd_lit,
      sym_escape,
      sym__form,
      sym_field_access,
      sym__expr,
      sym_list_lit,
      sym_element,
  [847] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_DQUOTE,
    ACTIONS(87), 1,
      anon_sym_SQUOTE,
    ACTIONS(91), 1,
      anon_sym_COLON,
    ACTIONS(93), 1,
      anon_sym_BSLASH,
    ACTIONS(95), 1,
      anon_sym_LBRACK,
    ACTIONS(97), 1,
      anon_sym_LPAREN,
    ACTIONS(103), 1,
      sym_ident,
    ACTIONS(223), 1,
      sym_int_lit,
    ACTIONS(89), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(81), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(16), 11,
      sym_sym,
      sym_str_lit,
      sym_bool_lit,
      sym_kwd_lit,
      sym_escape,
      sym__form,
      sym_field_access,
      sym__expr,
      sym_list_lit,
      sym_element,
      aux_sym__templ_body_repeat1,
  [898] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_DQUOTE,
    ACTIONS(87), 1,
      anon_sym_SQUOTE,
    ACTIONS(91), 1,
      anon_sym_COLON,
    ACTIONS(93), 1,
      anon_sym_BSLASH,
    ACTIONS(95), 1,
      anon_sym_LBRACK,
    ACTIONS(97), 1,
      anon_sym_LPAREN,
    ACTIONS(103), 1,
      sym_ident,
    ACTIONS(113), 1,
      sym_int_lit,
    STATE(13), 1,
      aux_sym_list_lit_repeat1,
    ACTIONS(89), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(81), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(62), 10,
      sym_sym,
      sym_str_lit,
      sym_bool_lit,
      sym_kwd_lit,
      sym_escape,
      sym__form,
      sym_field_access,
      sym__expr,
      sym_list_lit,
      sym_element,
  [951] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_ident,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    ACTIONS(21), 1,
      anon_sym_COLON,
    ACTIONS(27), 1,
      anon_sym_LPAREN,
    ACTIONS(225), 1,
      sym_int_lit,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(11), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(90), 7,
      sym_sym,
      sym_str_lit,
      sym_bool_lit,
      sym_kwd_lit,
      sym_field_access,
      sym__expr,
      sym_list_lit,
  [992] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_ident,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    ACTIONS(21), 1,
      anon_sym_COLON,
    ACTIONS(27), 1,
      anon_sym_LPAREN,
    ACTIONS(227), 1,
      sym_int_lit,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(11), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(88), 7,
      sym_sym,
      sym_str_lit,
      sym_bool_lit,
      sym_kwd_lit,
      sym_field_access,
      sym__expr,
      sym_list_lit,
  [1033] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 1,
      anon_sym_DOT,
    ACTIONS(231), 5,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_record,
      anon_sym_templ,
    ACTIONS(229), 13,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [1062] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 5,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_record,
      anon_sym_templ,
    ACTIONS(235), 13,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [1088] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 5,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_record,
      anon_sym_templ,
    ACTIONS(239), 13,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [1114] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 5,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_record,
      anon_sym_templ,
    ACTIONS(243), 13,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [1140] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 1,
      anon_sym_DOT,
    ACTIONS(231), 4,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_end,
    ACTIONS(229), 13,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RBRACK,
  [1168] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 5,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_record,
      anon_sym_templ,
    ACTIONS(249), 13,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [1194] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 5,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_record,
      anon_sym_templ,
    ACTIONS(239), 13,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [1220] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(255), 5,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_record,
      anon_sym_templ,
    ACTIONS(253), 13,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [1246] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 5,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_record,
      anon_sym_templ,
    ACTIONS(257), 13,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [1272] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(263), 5,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_record,
      anon_sym_templ,
    ACTIONS(261), 13,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [1298] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 5,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_record,
      anon_sym_templ,
    ACTIONS(265), 12,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [1323] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 1,
      sym_ident,
    ACTIONS(274), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(36), 2,
      sym_attr,
      aux_sym_attrs_repeat1,
    ACTIONS(272), 12,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RBRACK,
  [1352] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(276), 4,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_end,
    ACTIONS(278), 13,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RBRACK,
  [1377] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(280), 4,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_end,
    ACTIONS(282), 13,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RBRACK,
  [1402] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(284), 4,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_end,
    ACTIONS(286), 13,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RBRACK,
  [1427] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(290), 5,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_record,
      anon_sym_templ,
    ACTIONS(288), 12,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [1452] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 4,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_end,
    ACTIONS(249), 13,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RBRACK,
  [1477] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(292), 4,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_end,
    ACTIONS(294), 13,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RBRACK,
  [1502] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 4,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_end,
    ACTIONS(239), 13,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RBRACK,
  [1527] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 4,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_end,
    ACTIONS(239), 13,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RBRACK,
  [1552] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 1,
      anon_sym_DOT,
    ACTIONS(296), 1,
      anon_sym_EQ,
    ACTIONS(231), 3,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(229), 12,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RBRACK,
  [1581] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(292), 5,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_record,
      anon_sym_templ,
    ACTIONS(294), 12,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [1606] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(263), 4,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_end,
    ACTIONS(261), 13,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RBRACK,
  [1631] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(298), 1,
      sym_ident,
    ACTIONS(302), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(36), 2,
      sym_attr,
      aux_sym_attrs_repeat1,
    ACTIONS(300), 12,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RBRACK,
  [1660] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(306), 5,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_record,
      anon_sym_templ,
    ACTIONS(304), 12,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [1685] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 4,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_end,
    ACTIONS(265), 13,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RBRACK,
  [1710] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 4,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_end,
    ACTIONS(243), 13,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RBRACK,
  [1735] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 4,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_end,
    ACTIONS(235), 13,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RBRACK,
  [1760] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 4,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_end,
    ACTIONS(257), 13,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RBRACK,
  [1785] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(255), 4,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_end,
    ACTIONS(253), 13,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RBRACK,
  [1810] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(310), 5,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_record,
      anon_sym_templ,
    ACTIONS(308), 12,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [1835] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(284), 5,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_record,
      anon_sym_templ,
    ACTIONS(286), 12,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [1860] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(276), 5,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_record,
      anon_sym_templ,
    ACTIONS(278), 12,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [1885] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(280), 5,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_record,
      anon_sym_templ,
    ACTIONS(282), 12,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [1910] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(314), 5,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_record,
      anon_sym_templ,
    ACTIONS(312), 12,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [1935] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(318), 5,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_record,
      anon_sym_templ,
    ACTIONS(316), 12,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [1960] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(320), 3,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(322), 12,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RBRACK,
  [1983] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(324), 3,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(326), 12,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [2006] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(328), 3,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(330), 12,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_int_lit,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RBRACK,
  [2029] = 5,
    ACTIONS(332), 1,
      sym_comment,
    ACTIONS(334), 1,
      anon_sym_DQUOTE,
    ACTIONS(339), 1,
      anon_sym_BSLASH_LPAREN,
    STATE(64), 1,
      aux_sym_str_lit_repeat1,
    ACTIONS(336), 2,
      aux_sym_str_lit_token1,
      sym_escape_char,
  [2046] = 5,
    ACTIONS(332), 1,
      sym_comment,
    ACTIONS(342), 1,
      anon_sym_BSLASH_LPAREN,
    ACTIONS(344), 1,
      anon_sym_SQUOTE,
    STATE(68), 1,
      aux_sym_str_lit_repeat2,
    ACTIONS(346), 2,
      aux_sym_str_lit_token2,
      sym_escape_char,
  [2063] = 5,
    ACTIONS(332), 1,
      sym_comment,
    ACTIONS(348), 1,
      anon_sym_DQUOTE,
    ACTIONS(352), 1,
      anon_sym_BSLASH_LPAREN,
    STATE(70), 1,
      aux_sym_str_lit_repeat1,
    ACTIONS(350), 2,
      aux_sym_str_lit_token1,
      sym_escape_char,
  [2080] = 5,
    ACTIONS(332), 1,
      sym_comment,
    ACTIONS(342), 1,
      anon_sym_BSLASH_LPAREN,
    ACTIONS(348), 1,
      anon_sym_SQUOTE,
    STATE(69), 1,
      aux_sym_str_lit_repeat2,
    ACTIONS(354), 2,
      aux_sym_str_lit_token2,
      sym_escape_char,
  [2097] = 5,
    ACTIONS(332), 1,
      sym_comment,
    ACTIONS(356), 1,
      anon_sym_BSLASH_LPAREN,
    ACTIONS(359), 1,
      anon_sym_SQUOTE,
    STATE(68), 1,
      aux_sym_str_lit_repeat2,
    ACTIONS(361), 2,
      aux_sym_str_lit_token2,
      sym_escape_char,
  [2114] = 5,
    ACTIONS(332), 1,
      sym_comment,
    ACTIONS(342), 1,
      anon_sym_BSLASH_LPAREN,
    ACTIONS(364), 1,
      anon_sym_SQUOTE,
    STATE(68), 1,
      aux_sym_str_lit_repeat2,
    ACTIONS(346), 2,
      aux_sym_str_lit_token2,
      sym_escape_char,
  [2131] = 5,
    ACTIONS(332), 1,
      sym_comment,
    ACTIONS(352), 1,
      anon_sym_BSLASH_LPAREN,
    ACTIONS(366), 1,
      anon_sym_DQUOTE,
    STATE(64), 1,
      aux_sym_str_lit_repeat1,
    ACTIONS(368), 2,
      aux_sym_str_lit_token1,
      sym_escape_char,
  [2148] = 5,
    ACTIONS(332), 1,
      sym_comment,
    ACTIONS(342), 1,
      anon_sym_BSLASH_LPAREN,
    ACTIONS(370), 1,
      anon_sym_SQUOTE,
    STATE(65), 1,
      aux_sym_str_lit_repeat2,
    ACTIONS(372), 2,
      aux_sym_str_lit_token2,
      sym_escape_char,
  [2165] = 5,
    ACTIONS(332), 1,
      sym_comment,
    ACTIONS(352), 1,
      anon_sym_BSLASH_LPAREN,
    ACTIONS(370), 1,
      anon_sym_DQUOTE,
    STATE(73), 1,
      aux_sym_str_lit_repeat1,
    ACTIONS(374), 2,
      aux_sym_str_lit_token1,
      sym_escape_char,
  [2182] = 5,
    ACTIONS(332), 1,
      sym_comment,
    ACTIONS(352), 1,
      anon_sym_BSLASH_LPAREN,
    ACTIONS(376), 1,
      anon_sym_DQUOTE,
    STATE(64), 1,
      aux_sym_str_lit_repeat1,
    ACTIONS(368), 2,
      aux_sym_str_lit_token1,
      sym_escape_char,
  [2199] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(378), 1,
      sym_ident,
    ACTIONS(380), 1,
      anon_sym_end,
    STATE(75), 2,
      sym_field,
      aux_sym_fields_repeat1,
  [2213] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(382), 1,
      sym_ident,
    ACTIONS(385), 1,
      anon_sym_end,
    STATE(75), 2,
      sym_field,
      aux_sym_fields_repeat1,
  [2227] = 2,
    ACTIONS(332), 1,
      sym_comment,
    ACTIONS(387), 4,
      anon_sym_BSLASH_LPAREN,
      anon_sym_SQUOTE,
      aux_sym_str_lit_token2,
      sym_escape_char,
  [2237] = 2,
    ACTIONS(332), 1,
      sym_comment,
    ACTIONS(389), 4,
      anon_sym_DQUOTE,
      aux_sym_str_lit_token1,
      anon_sym_BSLASH_LPAREN,
      sym_escape_char,
  [2247] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(391), 1,
      sym_ident,
    ACTIONS(393), 1,
      anon_sym_LBRACK_RBRACK,
    STATE(101), 2,
      sym__type,
      sym_slice_lit,
  [2261] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(395), 1,
      sym_ident,
    STATE(89), 1,
      sym_fields,
    STATE(74), 2,
      sym_field,
      aux_sym_fields_repeat1,
  [2275] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      anon_sym_COLON,
    ACTIONS(397), 1,
      sym_ident,
    STATE(6), 1,
      sym_kwd_lit,
  [2288] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(399), 1,
      anon_sym_end,
    ACTIONS(401), 1,
      anon_sym_do,
    STATE(87), 1,
      sym__record_body,
  [2301] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(403), 1,
      anon_sym_end,
    ACTIONS(405), 1,
      anon_sym_do,
    STATE(104), 1,
      sym__templ_body,
  [2314] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      anon_sym_COLON,
    ACTIONS(407), 1,
      sym_ident,
    STATE(7), 1,
      sym_kwd_lit,
  [2327] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(409), 2,
      sym_ident,
      anon_sym_end,
  [2335] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(411), 2,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [2343] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(413), 2,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [2351] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(415), 1,
      anon_sym_end,
  [2358] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(417), 1,
      anon_sym_RPAREN,
  [2365] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(419), 1,
      anon_sym_end,
  [2372] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(421), 1,
      anon_sym_RPAREN,
  [2379] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(423), 1,
      sym_ident,
  [2386] = 2,
    ACTIONS(332), 1,
      sym_comment,
    ACTIONS(425), 1,
      aux_sym_attr_token1,
  [2393] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(427), 1,
      sym_ident,
  [2400] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(429), 1,
      ts_builtin_sym_end,
  [2407] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(431), 1,
      sym_ident,
  [2414] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(433), 1,
      anon_sym_SEMI,
  [2421] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(435), 1,
      sym_ident,
  [2428] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(437), 1,
      sym_ident,
  [2435] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(439), 1,
      anon_sym_SEMI,
  [2442] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(441), 1,
      sym_ident,
  [2449] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(443), 1,
      anon_sym_SEMI,
  [2456] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(445), 1,
      sym_ident,
  [2463] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(447), 1,
      sym_ident,
  [2470] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(449), 1,
      anon_sym_end,
  [2477] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(451), 1,
      sym_ident,
  [2484] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(296), 1,
      anon_sym_EQ,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(6)] = 0,
  [SMALL_STATE(7)] = 63,
  [SMALL_STATE(8)] = 126,
  [SMALL_STATE(9)] = 182,
  [SMALL_STATE(10)] = 238,
  [SMALL_STATE(11)] = 294,
  [SMALL_STATE(12)] = 350,
  [SMALL_STATE(13)] = 406,
  [SMALL_STATE(14)] = 462,
  [SMALL_STATE(15)] = 518,
  [SMALL_STATE(16)] = 572,
  [SMALL_STATE(17)] = 626,
  [SMALL_STATE(18)] = 682,
  [SMALL_STATE(19)] = 738,
  [SMALL_STATE(20)] = 794,
  [SMALL_STATE(21)] = 847,
  [SMALL_STATE(22)] = 898,
  [SMALL_STATE(23)] = 951,
  [SMALL_STATE(24)] = 992,
  [SMALL_STATE(25)] = 1033,
  [SMALL_STATE(26)] = 1062,
  [SMALL_STATE(27)] = 1088,
  [SMALL_STATE(28)] = 1114,
  [SMALL_STATE(29)] = 1140,
  [SMALL_STATE(30)] = 1168,
  [SMALL_STATE(31)] = 1194,
  [SMALL_STATE(32)] = 1220,
  [SMALL_STATE(33)] = 1246,
  [SMALL_STATE(34)] = 1272,
  [SMALL_STATE(35)] = 1298,
  [SMALL_STATE(36)] = 1323,
  [SMALL_STATE(37)] = 1352,
  [SMALL_STATE(38)] = 1377,
  [SMALL_STATE(39)] = 1402,
  [SMALL_STATE(40)] = 1427,
  [SMALL_STATE(41)] = 1452,
  [SMALL_STATE(42)] = 1477,
  [SMALL_STATE(43)] = 1502,
  [SMALL_STATE(44)] = 1527,
  [SMALL_STATE(45)] = 1552,
  [SMALL_STATE(46)] = 1581,
  [SMALL_STATE(47)] = 1606,
  [SMALL_STATE(48)] = 1631,
  [SMALL_STATE(49)] = 1660,
  [SMALL_STATE(50)] = 1685,
  [SMALL_STATE(51)] = 1710,
  [SMALL_STATE(52)] = 1735,
  [SMALL_STATE(53)] = 1760,
  [SMALL_STATE(54)] = 1785,
  [SMALL_STATE(55)] = 1810,
  [SMALL_STATE(56)] = 1835,
  [SMALL_STATE(57)] = 1860,
  [SMALL_STATE(58)] = 1885,
  [SMALL_STATE(59)] = 1910,
  [SMALL_STATE(60)] = 1935,
  [SMALL_STATE(61)] = 1960,
  [SMALL_STATE(62)] = 1983,
  [SMALL_STATE(63)] = 2006,
  [SMALL_STATE(64)] = 2029,
  [SMALL_STATE(65)] = 2046,
  [SMALL_STATE(66)] = 2063,
  [SMALL_STATE(67)] = 2080,
  [SMALL_STATE(68)] = 2097,
  [SMALL_STATE(69)] = 2114,
  [SMALL_STATE(70)] = 2131,
  [SMALL_STATE(71)] = 2148,
  [SMALL_STATE(72)] = 2165,
  [SMALL_STATE(73)] = 2182,
  [SMALL_STATE(74)] = 2199,
  [SMALL_STATE(75)] = 2213,
  [SMALL_STATE(76)] = 2227,
  [SMALL_STATE(77)] = 2237,
  [SMALL_STATE(78)] = 2247,
  [SMALL_STATE(79)] = 2261,
  [SMALL_STATE(80)] = 2275,
  [SMALL_STATE(81)] = 2288,
  [SMALL_STATE(82)] = 2301,
  [SMALL_STATE(83)] = 2314,
  [SMALL_STATE(84)] = 2327,
  [SMALL_STATE(85)] = 2335,
  [SMALL_STATE(86)] = 2343,
  [SMALL_STATE(87)] = 2351,
  [SMALL_STATE(88)] = 2358,
  [SMALL_STATE(89)] = 2365,
  [SMALL_STATE(90)] = 2372,
  [SMALL_STATE(91)] = 2379,
  [SMALL_STATE(92)] = 2386,
  [SMALL_STATE(93)] = 2393,
  [SMALL_STATE(94)] = 2400,
  [SMALL_STATE(95)] = 2407,
  [SMALL_STATE(96)] = 2414,
  [SMALL_STATE(97)] = 2421,
  [SMALL_STATE(98)] = 2428,
  [SMALL_STATE(99)] = 2435,
  [SMALL_STATE(100)] = 2442,
  [SMALL_STATE(101)] = 2449,
  [SMALL_STATE(102)] = 2456,
  [SMALL_STATE(103)] = 2463,
  [SMALL_STATE(104)] = 2470,
  [SMALL_STATE(105)] = 2477,
  [SMALL_STATE(106)] = 2484,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(100),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(103),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(86),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [69] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(100),
  [72] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(93),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 2, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [119] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_list_lit_repeat1, 2, 0, 9), SHIFT_REPEAT(29),
  [122] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_lit_repeat1, 2, 0, 9), SHIFT_REPEAT(54),
  [125] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_lit_repeat1, 2, 0, 9), SHIFT_REPEAT(62),
  [128] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_lit_repeat1, 2, 0, 9), SHIFT_REPEAT(72),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_lit_repeat1, 2, 0, 9),
  [133] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_lit_repeat1, 2, 0, 9), SHIFT_REPEAT(71),
  [136] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_list_lit_repeat1, 2, 0, 9), SHIFT_REPEAT(53),
  [139] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_lit_repeat1, 2, 0, 9), SHIFT_REPEAT(95),
  [142] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_lit_repeat1, 2, 0, 9), SHIFT_REPEAT(85),
  [145] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_lit_repeat1, 2, 0, 9), SHIFT_REPEAT(83),
  [148] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_lit_repeat1, 2, 0, 9), SHIFT_REPEAT(20),
  [151] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__templ_body_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [154] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__templ_body_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [157] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__templ_body_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [160] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__templ_body_repeat1, 2, 0, 0), SHIFT_REPEAT(72),
  [163] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__templ_body_repeat1, 2, 0, 0), SHIFT_REPEAT(71),
  [166] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__templ_body_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [169] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__templ_body_repeat1, 2, 0, 0), SHIFT_REPEAT(95),
  [172] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__templ_body_repeat1, 2, 0, 0), SHIFT_REPEAT(85),
  [175] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__templ_body_repeat1, 2, 0, 0), SHIFT_REPEAT(83),
  [178] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__templ_body_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [181] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__templ_body_repeat1, 2, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__templ_body, 2, 0, 14),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [189] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__elements, 2, 0, 0), SHIFT_REPEAT(29),
  [192] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__elements, 2, 0, 0), SHIFT_REPEAT(54),
  [195] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__elements, 2, 0, 0), SHIFT_REPEAT(63),
  [198] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__elements, 2, 0, 0), SHIFT_REPEAT(72),
  [201] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__elements, 2, 0, 0), SHIFT_REPEAT(71),
  [204] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__elements, 2, 0, 0), SHIFT_REPEAT(53),
  [207] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__elements, 2, 0, 0), SHIFT_REPEAT(95),
  [210] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__elements, 2, 0, 0), SHIFT_REPEAT(85),
  [213] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__elements, 2, 0, 0), SHIFT_REPEAT(83),
  [216] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__elements, 2, 0, 0), SHIFT_REPEAT(20),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__elements, 2, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr, 1, 0, 0),
  [231] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expr, 1, 0, 0),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_str_lit, 2, 0, 0),
  [237] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_str_lit, 2, 0, 0),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_str_lit, 3, 0, 5),
  [241] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_str_lit, 3, 0, 5),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_kwd_lit, 2, 0, 1),
  [245] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_kwd_lit, 2, 0, 1),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_lit, 3, 0, 8),
  [251] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list_lit, 3, 0, 8),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sym, 1, 0, 0),
  [255] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sym, 1, 0, 0),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bool_lit, 1, 0, 0),
  [259] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bool_lit, 1, 0, 0),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_access, 3, 0, 4),
  [263] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field_access, 3, 0, 4),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_escape, 2, 0, 0),
  [267] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_escape, 2, 0, 0),
  [269] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_attrs_repeat1, 2, 0, 0), SHIFT_REPEAT(106),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_attrs_repeat1, 2, 0, 0),
  [274] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_attrs_repeat1, 2, 0, 0),
  [276] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 5, 0, 18),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 5, 0, 18),
  [280] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 4, 0, 13),
  [282] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 4, 0, 13),
  [284] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 4, 0, 12),
  [286] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 4, 0, 12),
  [288] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_namespace, 3, 0, 3),
  [290] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_namespace, 3, 0, 3),
  [292] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 3, 0, 7),
  [294] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 3, 0, 7),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [298] = {.entry = {.count = 1, .reusable = false}}, SHIFT(106),
  [300] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attrs, 1, 0, 0),
  [302] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attrs, 1, 0, 0),
  [304] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def_record, 3, 0, 10),
  [306] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_def_record, 3, 0, 10),
  [308] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def_templ, 5, 0, 19),
  [310] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_def_templ, 5, 0, 19),
  [312] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def_templ, 4, 0, 16),
  [314] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_def_templ, 4, 0, 16),
  [316] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def_record, 4, 0, 15),
  [318] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_def_record, 4, 0, 15),
  [320] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attr, 3, 0, 17),
  [322] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attr, 3, 0, 17),
  [324] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_list_lit_repeat1, 1, 0, 2),
  [326] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_lit_repeat1, 1, 0, 2),
  [328] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__elements, 1, 0, 0),
  [330] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__elements, 1, 0, 0),
  [332] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [334] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_str_lit_repeat1, 2, 0, 6),
  [336] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_str_lit_repeat1, 2, 0, 6), SHIFT_REPEAT(64),
  [339] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_str_lit_repeat1, 2, 0, 6), SHIFT_REPEAT(23),
  [342] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [344] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [346] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [348] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [350] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [352] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [354] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [356] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_str_lit_repeat2, 2, 0, 6), SHIFT_REPEAT(24),
  [359] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_str_lit_repeat2, 2, 0, 6),
  [361] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_str_lit_repeat2, 2, 0, 6), SHIFT_REPEAT(68),
  [364] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [366] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [368] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [370] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [372] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [374] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [376] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [378] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [380] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fields, 1, 0, 0),
  [382] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fields_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [385] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_fields_repeat1, 2, 0, 0),
  [387] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_str_lit_repeat2, 3, 0, 11),
  [389] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_str_lit_repeat1, 3, 0, 11),
  [391] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [393] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [395] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [397] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [399] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [401] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [403] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [405] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [407] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [409] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field, 3, 0, 20),
  [411] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [413] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [415] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [417] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [419] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__record_body, 2, 0, 14),
  [421] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [423] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [425] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [427] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [429] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [431] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [433] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slice_lit, 2, 0, 1),
  [435] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [437] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [439] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [441] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [443] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [445] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [447] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [449] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [451] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_tel(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_ident,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
